### ISSUE TITLE
emailconfirmation

### ISSUE THREAD

**Issue by issackelly** [pennersr/django-allauth#1]
$ python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_manager(settings)
  File "/Users/issackelly/virtualenvs/try-django-allauth/lib/python2.7/site-packages/django/core/management/**init**.py", line 438, in execute_manager
    utility.execute()
  File "/Users/issackelly/virtualenvs/try-django-allauth/lib/python2.7/site-packages/django/core/management/**init**.py", line 379, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/issackelly/virtualenvs/try-django-allauth/lib/python2.7/site-packages/django/core/management/base.py", line 191, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/Users/issackelly/virtualenvs/try-django-allauth/lib/python2.7/site-packages/django/core/management/base.py", line 219, in execute
    self.validate()
  File "/Users/issackelly/virtualenvs/try-django-allauth/lib/python2.7/site-packages/django/core/management/base.py", line 249, in validate
    num_errors = get_validation_errors(s, app)
  File "/Users/issackelly/virtualenvs/try-django-allauth/lib/python2.7/site-packages/django/core/management/validation.py", line 28, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/Users/issackelly/virtualenvs/try-django-allauth/lib/python2.7/site-packages/django/db/models/loading.py", line 146, in get_app_errors
    self._populate()
  File "/Users/issackelly/virtualenvs/try-django-allauth/lib/python2.7/site-packages/django/db/models/loading.py", line 64, in _populate
    self.load_app(app_name)
  File "/Users/issackelly/virtualenvs/try-django-allauth/lib/python2.7/site-packages/django/db/models/loading.py", line 78, in load_app
    models = import_module('.models', app_name)
  File "/Users/issackelly/virtualenvs/try-django-allauth/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/issackelly/virtualenvs/try-django-allauth/lib/python2.7/site-packages/allauth/account/models.py", line 12, in <module>
    from emailconfirmation.models import EmailAddress, EmailConfirmation
ImportError: No module named emailconfirmation.models

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1
