### ISSUE TITLE
Broken Pipe error?

### ISSUE THREAD

**Issue by EyesBear** [pennersr/django-allauth#1175]
After I put the following to one of my pages:
```
{% load socialaccount %}
{% providers_media_js %}
<a href="{% provider_login_url "facebook" method="js_sdk" %}">Facebook Connect</a>		
```
I receive such error on the backend:
```
Exception happened during processing of request from ('127.0.0.1', 58891)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 129, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
[03/Nov/2015 10:21:42] "GET /about/ HTTP/1.1" 500 182624
```
Any ideas why? Thanks.

Edit: After I added Facebook's SOCIALACCOUNT_PROVIDERS in my settings.py the Broken pipe error disappeared, but I still receive the 500 error message.

**Comment by pennersr** [comment]
I am sorry, but this is not an issue in allauth... closing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1175
