### ISSUE TITLE
Allauth requires testing modules

### ISSUE THREAD

**Issue by julen** [pennersr/django-allauth#1187]
Since the upgrade to 0.24, Allauth complains about some testing/mocking modules being missing:
```python
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line()
  File "~/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "~/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "~/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "~/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "~/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/julen/dev/translate/pootle/pootle/apps/accounts/models.py", line 31, in <module>
    from allauth.account.models import EmailAddress
  File "~/allauth/account/models.py", line 16, in <module>
    from .utils import user_email
  File "~/allauth/account/utils.py", line 18, in <module>
    from allauth.compat import OrderedDict
  File "~/allauth/compat.py", line 12, in <module>
    from unittest.mock import Mock, patch  # noqa
ImportError: No module named mock
```

This is because the `compat` module mixes testing and non-testing code, and the module is being imported from regular app code (not testing code), hence the dependencies are missing.

I'd suggest to take away the testing-specific code from the `compat` module so that testing modules are not required on runtime.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1187
