### ISSUE TITLE
Extending allauth views

### ISSUE THREAD

**Issue by mitsest** [pennersr/django-allauth#1319]
Hey dude,
awesome work. I 've been using allauth for quite some time now and I was able to extend your views like so

```python
class CustomLoginView(LoginView):
    template_name = 'account/login.html'

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context.update({'signup_form': SignupForm})

        return context

```

I did this in order to display the signup form at the same page as the login form, without breaking any functionality from your views (which are required in order for the user to log in)

However, after django 1.8 I get the following stacktrace:
```

Traceback (most recent call last):
  File "C:/Users/mitsest/PycharmProjects/teh_end/teh_end/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\mitsest\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "C:\Users\mitsest\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\core\management\__init__.py", line 312, in execute
    django.setup()
  File "C:\Users\mitsest\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\mitsest\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\mitsest\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\apps\config.py", line 86, in create
    module = import_module(entry)
  File "C:\Users\mitsest\AppData\Local\Programs\Python\Python35-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\mitsest\PycharmProjects\teh_end\teh_end\index_page\__init__.py", line 2, in <module>
    from .urls import site
  File "C:\Users\mitsest\PycharmProjects\teh_end\teh_end\index_page\urls.py", line 1, in <module>
    from .views import IndexPageView
  File "C:\Users\mitsest\PycharmProjects\teh_end\teh_end\index_page\views.py", line 4, in <module>
    from allauth.account.views import LoginView, SignupView
  File "C:\Users\mitsest\AppData\Local\Programs\Python\Python35-32\lib\site-packages\allauth\account\views.py", line 19, in <module>
    from .forms import (
  File "C:\Users\mitsest\AppData\Local\Programs\Python\Python35-32\lib\site-packages\allauth\account\forms.py", line 207, in <module>
    class BaseSignupForm(_base_signup_form_class()):
  File "C:\Users\mitsest\AppData\Local\Programs\Python\Python35-32\lib\site-packages\allauth\account\forms.py", line 209, in BaseSignupForm
    max_length=get_username_max_length(),
  File "C:\Users\mitsest\AppData\Local\Programs\Python\Python35-32\lib\site-packages\allauth\utils.py", line 56, in get_username_max_length
    User = get_user_model()
  File "C:\Users\mitsest\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\contrib\auth\__init__.py", line 150, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "C:\Users\mitsest\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\apps\registry.py", line 199, in get_model
    self.check_models_ready()
  File "C:\Users\mitsest\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\apps\registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

I 'm pretty stucked here, as I can't find any other way to override /login and /signup urls, apart from overriding the view.

Thanks !

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1319
