### ISSUE TITLE
Exception while trying to signup with wrong email address.

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#1326]
Hey guys,

If I try to signup with an email address which doesn't exist I've got this error: (For example xyz434234@gmail.com)

`Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/allauth/account/views.py", line 174, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/allauth/account/views.py", line 69, in dispatch
    **kwargs)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/allauth/account/views.py", line 152, in dispatch
    **kwargs)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/allauth/account/views.py", line 85, in post
    response = self.form_valid(form)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/allauth/account/views.py", line 190, in form_valid
    self.get_success_url())
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/allauth/account/utils.py", line 167, in complete_signup
    signal_kwargs=signal_kwargs)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/allauth/account/utils.py", line 131, in perform_login
    send_email_confirmation(request, user, signup=signup)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/allauth/account/utils.py", line 296, in send_email_confirmation
    signup=signup)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/allauth/account/models.py", line 58, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/allauth/account/models.py", line 122, in send
    get_adapter().send_confirmation_mail(request, self, signup)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/allauth/account/adapter.py", line 369, in send_confirmation_mail
    ctx)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/allauth/account/adapter.py", line 110, in send_mail
    msg.send()
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/django/core/mail/message.py", line 303, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 107, in send_messages
    sent = self._send(message)
  File "/var/www/files/scripts/python_productive_env/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 123, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python2.7/smtplib.py", line 733, in sendmail
    raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {u'xyz434234@gmail.com': (450, '4.1.1 <xyz434234@gmail.com>: Recipient address rejected: unverified address: Address verification in progress')}`

This is my configuration:
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_SUBJECT_PREFIX = 'mysite.com'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = ''
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_FORM_CLASS = 'usermanagement.forms.SignupForm'
SOCIALACCOUNT_AUTO_SIGNUP = False
LOGIN_REDIRECT_URL = '/dashboard/'

Is this a bug or do I have to handle this case on my own?

**Comment by pennersr** [comment]
I think you've set your EMAIL_HOST directly to gmail, right? 

You're bumping into Django's default `fail_silently=False` when sending mail, see: https://docs.djangoproject.com/en/1.9/topics/email/

Typically, for production setups, mail is delivered to a local SMTP server first. If this delivery fails, something is really wrong, which explains the crash and why it is not gracefully handled. Once delivered to your local SMTP server, that server will attempt delivery to gmail only bump into the same error, but then outside the scope of Django.

If you insist on running this way, you could override the `send_mail` adapter method and change `msg.send()` into `msg.send(fail_silently=True)`.

**Comment by BertrandBordage** [comment]
Isn’t it possible to make a validation error or at least add a django message and redirect to the sign up page?
With the current behaviour, users will think that signup is broken.

**Comment by hashlash** [comment]
@pennersr did you mean that the exception should be handled by the SMTP server and not returned to Django? And just want to make sure, did you also mean that we shouldn't directly set the EMAIL_HOST to Gmail? I'm new to this and want to understand how things are usually best done.

In the case of signup process, I think it's common for a web application to just "fail silently" if a user used an invalid email address (excluding format error). Or at least return a validation error just like @BertrandBordage said.

**Comment by BertrandBordage** [comment]
For those annoyed by the 500 errors reports triggered by bots testing emails with non-existent domains, here is my solution.

Add this middleware to your project, and reference it in `MIDDLEWARE` (I’m not sure the order will matter in this case):
```python
from smtplib import SMTPRecipientsRefused

from django.contrib import messages
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _


class SMTPRecipientsRefusedMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        return self.get_response(request)

    def process_exception(self, request, exception):
        if isinstance(exception, SMTPRecipientsRefused):
            for recipient_email in exception.recipients:
                messages.error(
                    request, _('Unable to send an e-mail to “%s”. Is this the correct address?') % recipient_email
                )
            return redirect(request.META.get('HTTP_REFERER', 'account_signup'))
```

It will show an error message to users and redirect them to the page they were on. If it was a form view, the form will have lost its changes.
Note that it applies to the entire project, not just to django-allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1326
