### ISSUE TITLE
django-allauth 0.25, resetting password

### ISSUE THREAD

**Issue by bashu** [pennersr/django-allauth#1328]
```python
[13/Mar/2016 15:28:51] "GET /u/password/reset/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/vagrant/.virtualenv/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/vagrant/.virtualenv/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/vagrant/.virtualenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/vagrant/.virtualenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vagrant/.virtualenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/vagrant/.virtualenv/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 206, in get
    return self.render_to_response(self.get_context_data(form=form))
  File "/home/vagrant/.virtualenv/local/lib/python2.7/site-packages/allauth/account/views.py", line 574, in get_context_data
    self.redirect_field_name)
AttributeError: 'PasswordResetView' object has no attribute 'redirect_field_name'
```

**Comment by bashu** [comment]
hmm, downgraded to 0.24.1 and everything is working now

**Comment by pennersr** [comment]
See c6e1dab4b6a9c39852d7cfdbe909c2536850f478

**Comment by bashu** [comment]
thanks, that was fast!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1328
