### ISSUE TITLE
Error: TypeError: __init__() got an unexpected keyword argument 'request'

### ISSUE THREAD

**Issue by a70babat** [pennersr/django-allauth#1341]
I'm getting error when accessing login form:
```
Internal Server Error: /a/login/
Traceback (most recent call last):
  File "/home/ali/Desktop/torob.ir/.env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ali/Desktop/torob.ir/.env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ali/Desktop/torob.ir/.env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ali/Desktop/torob.ir/.env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/ali/Desktop/torob.ir/.env/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/ali/Desktop/torob.ir/.env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/ali/Desktop/torob.ir/.env/local/lib/python2.7/site-packages/allauth/account/views.py", line 98, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/home/ali/Desktop/torob.ir/.env/local/lib/python2.7/site-packages/allauth/account/views.py", line 66, in dispatch
    **kwargs)
  File "/home/ali/Desktop/torob.ir/.env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ali/Desktop/torob.ir/.env/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 213, in get
    return self.render_to_response(self.get_context_data())
  File "/home/ali/Desktop/torob.ir/.env/local/lib/python2.7/site-packages/allauth/account/views.py", line 123, in get_context_data
    ret = super(LoginView, self).get_context_data(**kwargs)
  File "/home/ali/Desktop/torob.ir/.env/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 122, in get_context_data
    kwargs['form'] = self.get_form()
  File "/home/ali/Desktop/torob.ir/.env/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 74, in get_form
    return form_class(**self.get_form_kwargs())
TypeError: __init__() got an unexpected keyword argument 'request'

```

I think the error is because of overriding get_form_kwargs method in this commit and adding request to form kwargs:
[https://github.com/pennersr/django-allauth/commit/ae472772c8f93bcb972205c9d7159051cf6f413a#diff-cd558fc945d668087c050c1a99f0172fR100](https://github.com/pennersr/django-allauth/commit/ae472772c8f93bcb972205c9d7159051cf6f413a#diff-cd558fc945d668087c050c1a99f0172fR100)

or there is something else wrong. I'musing django 1.9.4

**Comment by pennersr** [comment]
The built-in LoginForm has this in its `__init__`:

```
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(LoginForm, self).__init__(*args, **kwargs)
```

So, the extra `request` param is not passed any further. I suspect that you have plugged in custom forms, is that correct? If so, you need to make sure a similar construct as above is in place.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1341
