### ISSUE TITLE
Using custom adapter gives error: save() prohibited to prevent data loss due to unsaved related object 'user'.

### ISSUE THREAD

**Issue by MikiSoft** [pennersr/django-allauth#1346]
```
from allauth.account.adapter import DefaultAccountAdapter


class AccountAdapter(DefaultAccountAdapter):
    def save_user(self, request, user, form, commit=False):
        data = form.cleaned_data
        user.username = data.get('username')
        user.email = data.get('email')
        user.first_name = data.get('first_name')
        user.last_name = data.get('last_name')
        user.gender = data.get('gender')
        user.birth = data.get('birth')
        user.city = data.get('city')
        user.country = data.get('country')
        if 'password1' in data:
            user.set_password(data.get('password1'))
        else:
            user.set_unusable_password()
        self.populate_username(request, user)
        if commit:
            user.save()
        return user
```
I have the code from above in my adapters.py, and after I submit the the signup form the error shows which is in the title here. It appears that the problem is in the `allauth.account.utils.setup_user_email` method which is saving the EmailAddress object _before_ saving the User object:
```
...
    for a in addresses:
        a.user = user
        a.save()
    EmailAddress.objects.fill_cache_for_user(user, addresses)
    if (primary
            and email
            and email.lower() != primary.email.lower()):
        user_email(user, primary.email)
        user.save()
    return primary
```
The error is raised on the `a.save()` line. So, how to fix that - is it a bug or not?

**Comment by pennersr** [comment]
If I am not mistaken, `setup_user_email` is invoked after the adapter `save`, so after the user is saved. See `allauth.account.forms.SignUpForm.save`.  Could you paste a full stack trace?

**Comment by MikiSoft** [comment]
```
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/allauth/account/views.py", line 177, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/allauth/account/views.py", line 66, in dispatch
    **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/allauth/account/views.py", line 155, in dispatch
    **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/allauth/account/views.py", line 82, in post
    response = self.form_valid(form)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/allauth/account/views.py", line 192, in form_valid
    self.user = form.save(self.request)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/allauth/account/forms.py", line 318, in save
    setup_user_email(request, user, [])
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/allauth/account/utils.py", line 276, in setup_user_email
    a.save()
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/db/models/base.py", line 659, in save
    "unsaved related object '%s'." % field.name
ValueError: save() prohibited to prevent data loss due to unsaved related object 'user'.
```

**Comment by MikiSoft** [comment]
Hmm, I found the problem - it was `commit` parameter which was set to `False` instead of `True`, but I got now following error:
```
Traceback (most recent call last):
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/allauth/account/views.py", line 177, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/allauth/account/views.py", line 66, in dispatch
    **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/allauth/account/views.py", line 155, in dispatch
    **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/allauth/account/views.py", line 82, in post
    response = self.form_valid(form)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/allauth/account/views.py", line 192, in form_valid
    self.user = form.save(self.request)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/allauth/account/forms.py", line 316, in save
    self.custom_signup(request, user)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/allauth/account/forms.py", line 285, in custom_signup
    custom_form.save(user)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/contrib/auth/forms.py", line 99, in save
    user.save()
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/contrib/auth/base_user.py", line 74, in save
    super(AbstractBaseUser, self).save(*args, **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/db/models/base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/db/models/base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/db/models/base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/db/models/base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/mikisoft/django-dev/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: main_user.email
```

**Comment by MikiSoft** [comment]
I've fixed that too, the problem was with my SignupForm (in forms.py). This issue can be closed now.

**Comment by survivor956** [comment]
@MikiSoft  , after solving your issue, why you didn't post the solution ?! What was wrong with the forms.py ?

**Comment by GoldenRatio3** [comment]
@MikiSoft Would love to know the solution. I am currently having the same problem

**Comment by MikiSoft** [comment]
@survivor956 @GoldenRatio3 Here's the answer: https://stackoverflow.com/a/36515188

**Comment by survivor956** [comment]
@MikiSoft  hello, as far as I remember, the solution is I added a `save` method to the user creation form:

models.py:
```
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models


class Profile(AbstractUser):
    """ The Profile Class
    """
    CIVILITY_CHOICES = (
        ('M.', 'M.'),
        ('MME', 'Mme')
    )
    organization = models.CharField(max_length=30, blank=True)
    civility = models.CharField(max_length=3, choices=CIVILITY_CHOICES,
                                default='M.', verbose_name="Civilité")

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('profiles:detail', kwargs={'username': self.username})

    class Meta:
        permissions = (
            ("can_send_command", "Can send Command to Object"),
        )
```

The adapters.py:
```
from django.conf import settings
from allauth.account.adapter import DefaultAccountAdapter


class AccountAdapter(DefaultAccountAdapter):
    """
    The following adapter can be used to intervene in how User (Profile) instances are created, and populated with data
    """
    def is_open_for_signup(self, request):
        """
         The default function returns that is the same as ACCOUNT_ADAPTER in settings.py. You can override this method
         by returning True/False if you want to enable/disable socialaccount signup.
        :param request:
        :return: Boolean
        """
        return getattr(settings, 'ACCOUNT_ALLOW_REGISTRATION', True)

    def save_user(self, request, profile, form, commit=False):
        """
        Populates and saves the Profile instance using information provided in the signup form.
        :type request: Django HttpRequest
        :param request: Object containing metadata about the request

        :type profile: Profile
        :param profile: Object containing the new user

        :type form: UserCreationForm
        :param form: form filled by the user seeking sign up

        :type commit: Boolean
        :param commit: Saving with commit=False gets you a model object, then you can add your extra data and save it.

        :return: profile
        """
        data = form.cleaned_data
        profile.username = data['username']
        profile.email = data['email']
        profile.first_name = data['first_name']
        profile.last_name = data['last_name']
        profile.civility = data['civility']
        profile.organization = data['organization']
        if 'password1' in data:
            profile.set_password(data['password1'])
        else:
            profile.set_unusable_password()
        if commit:
            profile.save()
        return profile
```

And the forms.py
```
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Permission

from .models import Profile


class ProfileForm(UserCreationForm):
    email = forms.EmailField(required=True, label="E-mail")
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        # We define the used model
        model = Profile
        exclude = []
        fields = ("first_name", "last_name", "civility", "username", "organization", "email", "password1", "password2")

    def save(self, user):
        user.save()  # save the user object first so we can use it for relationships
        permission1 = Permission.objects.get(codename='read_object')
        permission2 = Permission.objects.get(codename='read_object2')
        user.user_permissions.add(permission1, permission2)
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1346
