### ISSUE TITLE
Social account error in signup

### ISSUE THREAD

**Issue by mhipo1364** [pennersr/django-allauth#1355]
I'm using `django-allauth` and its social, also I've overwritten `signup-form` by using `ACCOUNT_SIGNUP_FORM_CLASS` , but when I call `accounts/google/login` , in its call back I will get this:

`TypeError: __str__ returned non-string (type Error)
[pid: 7515|app: 0|req: 12/61] 46.101.144.38 () {46 vars in 1247 bytes} [Sat Apr 23 23:42:29 2016] GET /accounts/google/login/callback/?state=JRKLCcKg6C3K&code=4/OtoXqi4CxNzK8kN5X_9F5r5jenAFdwi_Z2VmAwZ5Q28 => generated 0 bytes in 868 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1342, in _nr_wsgi_application_wrapper_
    result = wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1342, in _nr_wsgi_application_wrapper_
    result = wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 434, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python2.7/dist-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 493, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 97, in technical_500_response
    html = reporter.get_traceback_html()
  File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 383, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 375, in get_traceback_data
    c['exception_value'] = smart_text(self.exc_value, errors='replace')
  File "/usr/local/lib/python2.7/dist-packages/django/utils/encoding.py", line 56, in smart_text
    return force_text(s, encoding, strings_only, errors)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/encoding.py", line 92, in force_text
    s = six.text_type(s)
TypeError: __str__ returned non-string (type Error)`

What the heck is its problem???

**Comment by pennersr** [comment]
I am sorry, but that stack trace is insufficient for me to help you any further.. closing, as this is not an issue in allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1355
