### ISSUE TITLE
GitHub provider throwing stacktraces

### ISSUE THREAD

**Issue by cro** [pennersr/django-allauth#1362]
Greetings,

We deployed a new version of our site today.  I've seen several stacktraces like the following, but can't reproduce this in my testing.  Has anyone seen this before?  Can you possibly give me a clue as to how to fix it?

I have evidence that other GitHub users are successfully creating accounts and getting logged into the site, so it's not failing for everyone.

Here's an excerpt from my settings.py:

```
SOCIALACCOUNT_PROVIDERS = \
    {'google':
         {'SCOPE': ['profile',
                    'email'],
          'AUTH_PARAMS': {'access_type': 'online'},
         },
     'github':
         {'SCOPES': ['user:email']},
    }
```

And the stacktrace:

```
Internal Server Error: /accounts/github/login/callback/
Traceback (most recent call last):
  File "/webroot/web/ssc3/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/webroot/web/ssc3/lib/python3.5/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 62, in view
    return self.dispatch(request, *args, **kwargs)
  File "/webroot/web/ssc3/lib/python3.5/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 126, in dispatch
    response=access_token)
  File "/webroot/web/ssc3/lib/python3.5/site-packages/allauth/socialaccount/providers/github/views.py", line 22, in complete_login
    extra_data['email'] = self.get_email(token)
  File "/webroot/web/ssc3/lib/python3.5/site-packages/allauth/socialaccount/providers/github/views.py", line 32, in get_email
    email = emails[0]
KeyError: 0

Request repr():
<WSGIRequest
path:/accounts/github/login/callback/,
GET:<QueryDict: {'state': ['<redacted>'], 'code': ['<redacted>']}>,
POST:<QueryDict: {}>,
COOKIES:{'__utma': '<redacted>',
 '__utmc': '<redacted>',
 '__utmz': '<redacted>',
 '_ga': '<redacted>',
 'csrftoken': '<redacted>',
 'sessionid': '<redacted>'},
META:{'CSRF_COOKIE': '<redacted>',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8',
 'HTTP_CONNECTION': 'close',
 'HTTP_COOKIE': '_ga=<redacted>; '
                '__utma=<redacted>; '
                '__utmc=<redacted>; '
                '__utmz=<redacted>=(organic)|utmcmd=organic|utmctr=(not%20provided); '
                'csrftoken=<redacted>; '
                'sessionid=<redacted>',
 'HTTP_HOST': '<redacted>',
 'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) '
                    'AppleWebKit/537.36 (KHTML, like Gecko) '
                    'Chrome/50.0.2661.86 Safari/537.36',
 'HTTP_X_FORWARDED_FOR': '<redacted>',
 'HTTP_X_REAL_IP': '<redacted>',
 'HTTP_X_SCHEME': 'https',
 'PATH_INFO': '/accounts/github/login/callback/',
 'QUERY_STRING': 'code=<redacted>&state=<redacted>',
 'RAW_URI': '/accounts/github/login/callback/?code=<redacted>&state=<redacted>',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '33103',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '0.0.0.0',
 'SERVER_PORT': '8000',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'gunicorn/19.4.5',
 'gunicorn.socket': <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 33103)>,
 'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x808a00828>,
 'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
 'wsgi.input': <gunicorn.http.body.Body object at 0x808a00908>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
```

**Comment by cro** [comment]
I'm going to close this.  I had the brainstorm to clean out the sessions table.  I think that made the stacktraces stop.  I'll open a new issue with more details if it recurs.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1362
