### ISSUE TITLE
file name too long

### ISSUE THREAD

**Issue by BenDevelopment** [pennersr/django-allauth#1498]
When I try to install django-allauth, I have an error:
```
Installing collected packages: django-allauth
Exception:
Traceback (most recent call last):
  File "c:\travail\coachmanager\cm-restful-service\cm_restful_service_project\cm_restful_service_project\env1\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\travail\coachmanager\cm-restful-service\cm_restful_service_project\cm_restful_service_project\env1\lib\site-packages\pip\commands\install.py", line 317, in run
    prefix=options.prefix_path,
  File "c:\travail\coachmanager\cm-restful-service\cm_restful_service_project\cm_restful_service_project\env1\lib\site-packages\pip\req\req_set.py", line 742, in install
    **kwargs
  File "c:\travail\coachmanager\cm-restful-service\cm_restful_service_project\cm_restful_service_project\env1\lib\site-packages\pip\req\req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\travail\coachmanager\cm-restful-service\cm_restful_service_project\cm_restful_service_project\env1\lib\site-packages\pip\req\req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "c:\travail\coachmanager\cm-restful-service\cm_restful_service_project\cm_restful_service_project\env1\lib\site-packages\pip\wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "c:\travail\coachmanager\cm-restful-service\cm_restful_service_project\cm_restful_service_project\env1\lib\site-packages\pip\wheel.py", line 324, in clobber
    shutil.copyfile(srcfile, destfile)
  File "c:\travail\coachmanager\cm-restful-service\cm_restful_service_project\cm_restful_service_project\env1\lib\shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\travail\\coachmanager\\cm-restful-service\\cm_restful_service_project\\cm_restful_service_project\\env1\\Lib\\site-packages\\allauth\\socialaccount\\providers\\facebook\\south_
migrations\\__pycache__\\0002_auto__add_facebookaccesstoken__add_unique_facebookaccesstoken_app_acco.cpython-35.pyc'
```

I'm using windows 10. How can I fix this problem ?

**Comment by pennersr** [comment]
On latest master, the south migrations have been removed

4a6df009ff98255e03a122eb9ea4a90c5eb2aa35

**Comment by BenDevelopment** [comment]
When will the source for pip install be updated?

**Comment by pennersr** [comment]
0.28.0 has just been released

**Comment by BenDevelopment** [comment]
Thank you.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1498
