### ISSUE TITLE
Django-Allauth custom signup ModelForm inheritance: no fields error

### ISSUE THREAD

**Issue by stefko18** [pennersr/django-allauth#1541]
I am adding my custom signup form in allauth:

`ACCOUNT_SIGNUP_FORM_CLASS` = `'myApp.forms.SignupDataForm'`

I have used the code in django 1.6 and allauth 0.18 but when trying it in django 1.8.6 and allauth 0.28 I get:

`AttributeError: 'SignupForm' object has no attribute `fields'`

My SignupForm is a child declared like this:

```
class SignupDataForm(BaseUserDataForm):

    reg_user_badge = forms.CharField(label="Give Points to a Friend",required=False,widget = TextInput(attrs={'placeholder': 'Username `(optional)'}),validators=[validate_friendname])`

class Meta(BaseUserDataForm.Meta):
    model = UserData
    fields = BaseUserDataForm.Meta.fields + ('terms_conditions',)
    #terms_conditions is also a model field but not added to the parent definition

def __init__(self, *args, **kwargs):
    super(SignupDataForm, self).__init__(*args, **kwargs)
    self.fields['terms_conditions'].required = False
    self.fields['gender'].widget = Select(choices=GENDER_CHOICES,attrs={'class':'signup_select',})
    self.fields['password2'].widget.attrs['onblur'] ="check_pass()"
    self.fields['password1'].widget.attrs['onblur'] ="check_pass()"


def clean(self):
    #clean overwrite

def signup(self,request, user):
    #requested signup `function`
```

What is weird is that if I feed Allauth with the parent form everything works fine, I get no error. The shortend code for the parent is here:

```
class BaseUserDataForm(forms.ModelForm):
    url = forms.CharField(max_length = 30, label="Don't type here (anti spam protection)",validators=[validate_name_honeypots])

class Meta:
    model = UserData
    fields = ('****model fields named without terms_conditions field****')

def __init__(self, *args, **kwargs):
    super(BaseUserDataForm, self).__init__(*args, **kwargs)`
```
And here is my traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/ubuntu/workspace/project/apps/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/ubuntu/workspace/project/apps/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/ubuntu/workspace/project/apps/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/ubuntu/workspace/project/apps/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/workspace/project/apps/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/workspace/project/apps/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/ubuntu/workspace/project/apps/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/ubuntu/workspace/project/apps/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/ubuntu/workspace/project/apps/allauth/account/views.py", line 175, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "/home/ubuntu/workspace/project/apps/allauth/account/views.py", line 69, in dispatch
    **kwargs)
  File "/home/ubuntu/workspace/project/apps/allauth/account/views.py", line 152, in dispatch
    **kwargs)
  File "/home/ubuntu/workspace/project/apps/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/workspace/project/apps/django/views/generic/edit.py", line 205, in get
    form = self.get_form()
  File "/home/ubuntu/workspace/project/apps/django/views/generic/edit.py", line 74, in get_form
    return form_class(**self.get_form_kwargs())
  File "/home/ubuntu/workspace/project/apps/allauth/account/forms.py", line 291, in __init__
    super(SignupForm, self).__init__(*args, **kwargs)
  File "/home/ubuntu/workspace/project/apps/allauth/account/forms.py", line 229, in __init__
    merged_field_order = list(self.fields.keys())
AttributeError: 'SignupForm' object has no attribute 'fields'
[26/Nov/2016 14:38:24] "GET /accounts/signup/ HTTP/1.1" 500 59
```

Does anybody know what am I doing wrong?

**Comment by stefko18** [comment]
Solved. Not an allauth issue at all. There was a form below, partialy wrapped and partially commented that I didn't see and it caused an intendention error that manifest it such a weird manner ....

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1541
