### ISSUE TITLE
All of my social logins started failing yesterday

### ISSUE THREAD

**Issue by dtougas** [pennersr/django-allauth#1713]
All of a sudden all of my social logins started failing yesterday, and an exception is getting thrown that does not make any sense to me. Here is a copy of the stack trace:

```
File "/var/www/mysite.com/env/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/var/www/mysite.com/env/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/var/www/mysite.com/env/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/var/www/mysite.com/env/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/www/mysite.com/env/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth2/views.py" in view
  69.                 return self.dispatch(request, *args, **kwargs)

File "/var/www/mysite.com/env/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth2/views.py" in dispatch
  124.             access_token = client.get_access_token(request.GET['code'])

File "/var/www/mysite.com/env/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth2/client.py" in get_access_token
  74.             auth=auth)

File "/var/www/mysite.com/env/lib/python2.7/site-packages/requests/api.py" in request
  56.         return session.request(method=method, url=url, **kwargs)

File "/var/www/mysite.com/env/lib/python2.7/site-packages/requests/sessions.py" in request
  488.         resp = self.send(prep, **send_kwargs)

File "/var/www/mysite.com/env/lib/python2.7/site-packages/requests/sessions.py" in send
  609.         r = adapter.send(request, **kwargs)

File "/var/www/mysite.com/env/lib/python2.7/site-packages/requests/adapters.py" in send
  423.                     timeout=timeout

File "/var/www/mysite.com/env/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py" in urlopen
  594.                                                   chunked=chunked)

File "/var/www/mysite.com/env/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py" in _make_request
  350.             self._validate_conn(conn)

File "/var/www/mysite.com/env/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py" in _validate_conn
  835.             conn.connect()

File "/var/www/mysite.com/env/lib/python2.7/site-packages/requests/packages/urllib3/connection.py" in connect
  311.                 cert_reqs=resolve_cert_reqs(self.cert_reqs),

File "/var/www/mysite.com/env/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py" in create_urllib3_context
  249.     context = SSLContext(ssl_version or ssl.PROTOCOL_SSLv23)

File "/var/www/mysite.com/env/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py" in __init__
  355.         self._ctx = OpenSSL.SSL.Context(self.protocol)

File "/var/www/mysite.com/env/lib/python2.7/site-packages/OpenSSL/SSL.py" in __init__
  614.             _openssl_assert(res == 1)

File "/var/www/mysite.com/env/lib/python2.7/site-packages/OpenSSL/_util.py" in openssl_assert
  67.             exception_from_error_queue(error)

File "/var/www/mysite.com/env/lib/python2.7/site-packages/OpenSSL/_util.py" in exception_from_error_queue
  54.     raise exception_type(errors)

Exception Type: Error at /accounts/facebook/login/callback/
Exception Value: []
```

Any thoughts on what could be causing this all of a sudden?

**Comment by jplehmann** [comment]
Our site is experiencing the same issue.  The first observed error was Apr 21 23:32:07 and it has been failing ever since for my Herkou-hosted service.  My stacktrace is slightly more readable and looks like:
```
[ERROR] Error accessing FB user profile  [views:76] 
Traceback (most recent call last): 
  File "/app/.heroku/python/lib/python2.7/site-packages/allauth/socialaccount/providers/facebook/views.py", line 71, in login_by_token 
    login = fb_complete_login(request, app, token) 
  File "/app/.heroku/python/lib/python2.7/site-packages/allauth/socialaccount/providers/facebook/views.py", line 24, in fb_complete_login 
    resp.raise_for_status() 
  File "/app/.heroku/python/lib/python2.7/site-packages/requests/models.py", line 831, in raise_for_status 
    raise HTTPError(http_error_msg, response=self) 
HTTPError: 400 Client Error: Bad Request 
```

I looked on the FB developer group and found one other person complaining about this. Then another developer said it started happening to him a month ago, caused by using an old library. https://www.facebook.com/groups/fbdevelopers/permalink/1387408337969343/

I am using a fairly old version: `django-allauth==0.20.0`.  I am guessing it uses a Facebook library which went from deprecated to unsupported.  Anyone else?

(Strangely, I also use a FB library to post to my page, and this one failed with `GraphAPIError: (#5) Unauthorized source IP address` but only 1 time and then it went back to working.  This was noted by [one person](https://www.facebook.com/groups/fbdevelopers/permalink/1388040077906169/) as well.)

**Comment by jplehmann** [comment]
@dtougas what version is your `allauth`?

**Comment by dtougas** [comment]
I am using 0.30.0. I am in the process of going through the various libraries to see if there is something that may need to be updated, but haven't resolved anything yet. Interestingly for me, this problem started happening all of a sudden for both Facebook and Twitter logins, so I doubt it is just Facebook.

**Comment by dtougas** [comment]
I just upgraded all of my packages related to allauth in a test environment, and I am still seeing the error.

**Comment by dtougas** [comment]
OK, I have just figured out the problem. It appears that another package that I recently installed brought in pyOpenssl as a dependency. Apparently when pyOpenssl is installed, django-allauth is using that, and that is where the error is being generated. If I uninstall pyOpenssl, the problem goes away.

**Comment by jplehmann** [comment]
@dtougas that was very helpful.  I found that my requests dependency had `pyopenssl.py`. Simply upgrading to latest `requests` fixed it for me.  (I also had 3 other packages which included their own version of requests but I didn't touch them).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1713
