### ISSUE TITLE
Setting "email" scope for google provider will result in an error.

### ISSUE THREAD

**Issue by abrinckm** [pennersr/django-allauth#1764]
Error: RelatedObjectDoesNotExist: EmailAddress has no user. (Full traceback below)

To reproduce... I have in settings.py:

```
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile', 'email'
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
```

Then I've hooked into `pre_social_login` signal to get profile info.

```
@receiver(pre_social_login)
def save_profile(request, sociallogin, **kwargs):
    logger.info(request)
    logger.info(vars(sociallogin))
```

That's it! It will result in this error after navigating to /accounts/google/login/ and selecting my google account to sign in with:

```
"GET /accounts/google/login/ HTTP/1.1" 302 0
<WSGIRequest: GET '/accounts/google/login/callback/?state=blah'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 325, in getMessage
    msg = str(self.msg)
  File "/Users/abrinckman/dev/breathe_project/env/lib/python2.7/site-packages/django/db/models/base.py", line 588, in __repr__
    u = six.text_type(self)
  File "/Users/abrinckman/dev/breathe_project/env/lib/python2.7/site-packages/allauth/account/models.py", line 40, in __str__
    return "%s (%s)" % (self.email, self.user)
  File "/Users/abrinckman/dev/breathe_project/env/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 194, in __get__
    "%s has no %s." % (self.field.model.__name__, self.field.name)
RelatedObjectDoesNotExist: EmailAddress has no user.
```

**Comment by abrinckm** [comment]
Upgrading my django-rest-auth and django-allauth solved this issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1764
