### ISSUE TITLE
Tests fail if `ACCOUNT_USER_MODEL_USERNAME_FIELD = None`

### ISSUE THREAD

**Issue by jakob-stoeck** [pennersr/django-allauth#1852]
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/tests.py#L165 has the attribute "username" hard-coded inside the test, resulting in two errors in the test suite if the username is deactivated in settings.py with `ACCOUNT_USER_MODEL_USERNAME_FIELD = None`.

The errors are very similar. One looks like this:

```
======================================================================
ERROR: test_account_tokens (external_services.providers.dropbox_oauth2.tests.DropboxOAuth2Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/allauth/socialaccount/tests.py", line 168, in test_account_tokens
    email=email)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 397, in create
    obj = self.model(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 68, in __init__
    super(AbstractBaseUser, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 555, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
TypeError: 'username' is an invalid keyword argument for this function
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1852
