### ISSUE TITLE
Double-clicking 'submit' button on sign-up form causes multiple users & IntegrityError

### ISSUE THREAD

**Issue by swizzard** [pennersr/django-allauth#1862]
When a user clicks the `submit` button on the sign-up form more than once before the next page loads, multiple users are created and an `IntegrityError` is thrown by the `account_emailaddress_email_key` constraint.

```
[2017-11-03 19:30:18,563] ERROR django.request Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python2.7/site-packages/allauth/account/views.py", line 210, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/allauth/account/views.py", line 79, in dispatch
    **kwargs)
  File "/usr/lib/python2.7/site-packages/allauth/account/views.py", line 188, in dispatch
    **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/allauth/account/views.py", line 102, in post
    response = self.form_valid(form)
  File "/usr/lib/python2.7/site-packages/allauth/account/views.py", line 231, in form_valid
    self.get_success_url())
  File "/usr/lib/python2.7/site-packages/allauth/account/utils.py", line 188, in complete_signup
    signal_kwargs=signal_kwargs)
  File "/usr/lib/python2.7/site-packages/allauth/account/utils.py", line 148, in perform_login
    send_email_confirmation(request, user, signup=signup)
  File "/usr/lib/python2.7/site-packages/allauth/account/utils.py", line 328, in send_email_confirmation
    confirm=True)
  File "/usr/lib/python2.7/site-packages/allauth/account/managers.py", line 15, in add_email
    user=user, email__iexact=email, defaults={"email": email}
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 407, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 447, in _create_object_from_params
    six.reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 439, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib/python2.7/site-packages/raven/contrib/django/client.py", line 112, in execute
    return real_execute(self, sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "account_emailaddress_email_key"
DETAIL:  Key (email)=(sam+3@xxxx.com) already exists.
```

**Comment by pennersr** [comment]
To prevent double click problems, make sure you disable the button using a bit of JS. Solving this goes beyond allauth scope as it may even be frontend framework dependent. Also, this holds for any form in your app...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1862
