### ISSUE TITLE
Adding Scope to coinbase results in key error 

### ISSUE THREAD

**Issue by jvilaikeo** [pennersr/django-allauth#1897]
Django Allauth works when the scope is unchanged but doesn't have permissions. I've tried several iterations and removing extra_data without any luck. Is there something I'm missing? 

default:
scope=user

When changed to:
scope=wallet%3Auser%3Aread in the URI there is a key error

The json data is populated with the right information, but the response is a <401> and I'm not sure where or why its doing that.

'users'

Internal Server Error: /accounts/coinbase/login/callback/
Traceback (most recent call last):
  File "/opt/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/local/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/local/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 134, in dispatch
    response=access_token)
  File "/opt/local/lib/python2.7/site-packages/allauth/socialaccount/providers/coinbase/views.py", line 30, in complete_login
    extra_data = response.json()['users'][0]['user']
KeyError: 'users'

**Comment by jvilaikeo** [comment]
Looks like the views.py is pointing to the old api version and providers is still on v1 of the coinbase api. I've updated the two but still get a key error 0 at the same spot.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1897
