### ISSUE TITLE
Authentication with StackOverflow is crashing

### ISSUE THREAD

**Issue by marcosvbras** [pennersr/django-allauth#1922]
When the login is perfomed, some accounts have the following error:

```
Internal Server Error: /v1/auth/account/stackexchange/login/callback/
Traceback (most recent call last):

 File "******/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
   response = get_response(request)

 File "******/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
   response = self.process_exception_by_middleware(e, request)

 File "******/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)

 File "******/env/vp-django/lib/python3.5/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 73, in view
   return self.dispatch(request, *args, **kwargs)

 File "******/lib/python3.5/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 134, in dispatch
   response=access_token)

 File "******/vp-django/lib/python3.5/site-packages/allauth/socialaccount/providers/stackexchange/views.py", line 25, in complete_login
   extra_data = resp.json()['items'][0]

IndexError: list index out of range
```

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1922
