### ISSUE TITLE
UnicodeDecodeError at instalation

### ISSUE THREAD

**Issue by stefko18** [pennersr/django-allauth#1976]
This is Ubuntu 14.04.5 LTS
Django 1.11.11

Whatever version of AllAuth I am trying to get I always see this:

Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 643, in unpack_file
    untar_file(filename, location)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 574, in untar_file
    path = os.path.join(location, fn)
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 47: ordinal not in range(128)

Storing debug log for failure in /home/ubuntu/.pip/pip.log

Any ideas how to solve that?

I found similar issues that solved this with setting locale to utf8, but my is set to utf8 .. i don't understand what is wrong here at all ...

**Comment by stefko18** [comment]
This is still not solved, I still can not install All Auth ..

**Comment by pennersr** [comment]
I don't see anything in the stacktrace that points to allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1976
