### ISSUE TITLE
Refreshing user tokens

### ISSUE THREAD

**Issue by daviddanielarch** [pennersr/django-allauth#2015]
In the last days we are getting 500 error pages when some users try to login. It looks like the problems is generated because of some token policy changes Facebook made recentrly.
https://developers.facebook.com/docs/facebook-login/access-tokens/refreshing

Here it states that:

> User access tokens are either short-lived or long-lived. However, all access tokens must be renewed every 90 days with the consent of the person using your app. This means that every 90 days you must send a person through the login process and they must agree to the login by clicking the Continue button.

```
Internal Server Error: /accounts/facebook/login/token/
Traceback (most recent call last):
  File "/home/meshh/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/meshh/venv/lib/python3.4/site-packages/allauth/socialaccount/providers/facebook/views.py", line 93, in login_by_token
    access_token = resp['access_token']
KeyError: 'access_token'
```
The error returned by the Graph API causing this error is **The access token is invalid since the user hasn't engaged the app in longer than 90 days**

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2015
