### ISSUE TITLE
Can't test /social/connections/ when Facebook app is included

### ISSUE THREAD

**Issue by kradem** [pennersr/django-allauth#2149]
```
Django==2.1.3
django-allauth==0.38.0
oauthlib==2.1.0
python3-openid==3.1.0
requests==2.20.1
requests-oauthlib==1.0.0
```

I am able to manually visit `/accounts/social/connections/` and succesfully run functional tests (`StaticLiveServerTestCase`) with these two providers/settings:

```
INSTALLED_APPS = [
    ...
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.twitter',
    ...
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email', ],
        'AUTH_PARAMS': {'access_type': 'online', }
    }
}
```
When I add `'allauth.socialaccount.providers.facebook'` to `INSTALLED_APPS` and Facebook configuration to `SOCIALACCOUNT_PROVIDERS` then I am able to manually visit the connections page (and do all the other social accounts related jobs like connecting to Facebook account), but my test fails both with Django test runner and with pytest/pytest-django test runner:

```
log.py                     228 ERROR    Internal Server Error: /accounts/social/connections/
Traceback (most recent call last):
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/allauth/socialaccount/providers/facebook/provider.py", line 141, in media_js
    app = self.get_app(request)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/allauth/socialaccount/providers/base.py", line 52, in get_app
    return SocialApp.objects.get_current(self.id, request)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/allauth/socialaccount/models.py", line 34, in get_current
    provider=provider)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
allauth.socialaccount.models.SocialApp.DoesNotExist: SocialApp matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 58, in render
    for p in providers.registry.get_list(request)])
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 58, in <listcomp>
    for p in providers.registry.get_list(request)])
  File "/home/kradem/.virtualenvs/project/lib/python3.6/site-packages/allauth/socialaccount/providers/facebook/provider.py", line 143, in media_js
    raise ImproperlyConfigured("No Facebook app configured: please"
django.core.exceptions.ImproperlyConfigured: No Facebook app configured: please add a SocialApp using the Django admin

```

That error raises even when `SOCIALACCOUNT_PROVIDERS` 'facebook' entry is missing.

**Comment by pennersr** [comment]
This is fixed by now.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2149
