### ISSUE TITLE
 binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by mw66** [pennersr/django-allauth#2176]
Try to login with Yahoo

test env: python3.6
django==2.1.5
python3-openid version_info = (3, 1, 0)

binascii.Error: Incorrect padding

Internal Server Error: /accounts/openid/login/
Traceback (most recent call last):
File "/home//project//src/mypy/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/home//project//src/mypy/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/home//project//src/mypy/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home//project//src/mypy/lib/python3.6/site-packages/allauth/socialaccount/providers/openid/views.py", line 43, in login
auth_request = client.begin(form.cleaned_data['openid'])
File "/home//project//src/mypy/lib/python3.6/site-packages/openid/consumer/consumer.py", line 359, in begin
return self.beginWithoutDiscovery(service, anonymous)
File "/home//project//src/mypy/lib/python3.6/site-packages/openid/consumer/consumer.py", line 382, in beginWithoutDiscovery
auth_req = self.consumer.begin(service)
File "/home//project//src/mypy/lib/python3.6/site-packages/openid/consumer/consumer.py", line 610, in begin
assoc = self._getAssociation(service_endpoint)
File "/home//project//src/mypy/lib/python3.6/site-packages/openid/consumer/consumer.py", line 1178, in _getAssociation
assoc = self.store.getAssociation(endpoint.server_url)
File "/home//project//src/mypy/lib/python3.6/site-packages/allauth/socialaccount/providers/openid/utils.py", line 104, in getAssociation
base64.decodestring(stored_assoc.secret.encode('utf-8')),
File "/home//project//src/mypy/lib/python3.6/base64.py", line 554, in decodestring
return decodebytes(s)
File "/home//project//src/mypy/lib/python3.6/base64.py", line 546, in decodebytes
return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
[2019-01-15 00:37:41,282 log.py:228 - log_response()] Internal Server Error: /accounts/openid/login/

**Comment by mingwugmail** [comment]
s = stored_assoc.secret
print(type(s), len(s), s)
<class 'str'> 33 b'InqXpun3BrFNCx+6FR2CTuVW71g=\n'

python3 bytes v.s. str is amazing.

**Comment by mingwugmail** [comment]
this hack seems fixed it: in 
    def getAssociation(self, server_url, handle=None):
line 101

```
       for stored_assoc in stored_assocs:
            s = stored_assoc.secret
            if s.startswith("b'"):
                s = s.split("'")[1].strip()
            if s.endswith("\\n"):
                s = s[:-2]
            assert((len(s) % 4) == 0)
            s = s.encode('utf-8')
            assoc = OIDAssociation(
                stored_assoc.handle,
                base64.decodestring(s),
                stored_assoc.issued, stored_assoc.lifetime,
                stored_assoc.assoc_type
            )
```

**Comment by pennersr** [comment]
Closing -- outdated.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2176
