### ISSUE TITLE
Trello provider needs some more detail

### ISSUE THREAD

**Issue by bastbnl** [pennersr/django-allauth#2178]
I'm trying to use the Trello provider on `Django==2.1.5`, `django-allauth==0.38.0` on python 3.5 to learn that it needs some documentation as using this provider differs a bit from the other providers.

Besides that  I ran into an issue: 
```
Traceback (most recent call last):
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/allauth/socialaccount/providers/oauth/views.py", line 41, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/allauth/socialaccount/providers/oauth/views.py", line 112, in dispatch
    response=access_token)
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/allauth/socialaccount/providers/trello/views.py", line 27, in complete_login
    token=urlquote(token),
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/django/utils/functional.py", line 195, in wrapper
    return func(*args, **kwargs)
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/django/utils/http.py", line 54, in urlquote
    return quote(url, safe)
  File "/usr/lib/python3.5/urllib/parse.py", line 713, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.5/urllib/parse.py", line 738, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```

I'll create a PR containing both documentation and a fix.

**Comment by pennersr** [comment]
There recently have been some Trello related changes. I assume that fixes this issue, if not, looking forward to a pull request.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2178
