### ISSUE TITLE
Request context not available for sign-up email, but is in password reset email

### ISSUE THREAD

**Issue by matburnham** [pennersr/django-allauth#2186]
I have a custom template tag to give me a fully qualified static URL to link images in emails:

```
# From https://stackoverflow.com/a/47336360

from django import template
from django.templatetags import static

register = template.Library()

class FullStaticNode(static.StaticNode):
    def url(self, context):
        print('context:', context)
        request = context['request']
        return request.build_absolute_uri(super().url(context))

@register.tag('fullstatic')
def do_static(parser, token):
    return FullStaticNode.handle_token(parser, token)
```

This necessarily uses context['request']. All works well when performing a password reset:

```
[19/Jan/2019 11:06:46] "GET /accounts/password/reset/ HTTP/1.1" 200 15173
context: [{'True': True, 'False': False, 'None': None},
  {'current_site': <Site: localhost>,
   'user': <User: meh>,
   'password_reset_url': 'http://192.168.88.88:8080/accounts/password/reset/key/2-534-3f0f3e0822219f075dfd/',
   'request': <WSGIRequest: POST '/accounts/password/reset/'>,
   'username': 'meh'}, {}]
[19/Jan/2019 11:06:49] "POST /accounts/password/reset/ HTTP/1.1" 302 0
[19/Jan/2019 11:06:49] "GET /accounts/password/reset/done/ HTTP/1.1" 200 14347
```

All goes slightly less well when I try to perform a sign-up as the request context is missing:
```
[19/Jan/2019 11:10:52] "GET /accounts/signup/ HTTP/1.1" 200 18541
context: [{'True': True, 'False': False, 'None': None},
  {'user': <User: meh>,
   'activate_url': 'http://192.168.88.88:8080/accounts/confirm-email/NA:1gkoXM:AmOrXCs_ucJGuNcJPE3q6dYjBBg/',
   'current_site': <Site: localhost>,
   'key': 'NA:1gkoXM:AmOrXCs_ucJGuNcJPE3q6dYjBBg'}, {}, {}]
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  ...
  File "/home/mat/virtualenvs/mysite/mysite/website/templatetags/fqurl.py", line 11, in url
    request = context['request']
  File "/home/mat/virtualenvs/mysite/lib/python3.6/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'request'
[19/Jan/2019 11:11:41] "POST /accounts/signup/ HTTP/1.1" 500 278287
```

While I can bodge round it using current_site instead, I was hoping to be able to reference whichever server was in use - dev, staging or production - without having to faff too much. I presume the context gets lost somewhere along the way with a signup, whereas the password reset has less to do before getting to sending the email?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2186
