### ISSUE TITLE
Five strange errors on openSUSE Tumbleweed, cern provider and KeyError: 'location' in openid

### ISSUE THREAD

**Issue by jayvdb** [pennersr/django-allauth#2210]
I am packaging allauth for openSUSE Tumbleweed, a rolling release using Django 2.1, and encountered three errors after getting all the dependency versions to be quite similar to eliminate potential errors caused by that.

Three errors related to Cern provider, all inherited.

Workaround:
```
rm allauth/socialaccount/providers/cern/tests.py
```

2 tests failing with KeyError: 'location' (not in response headers)

Workaround:
```
sed -i 's/test_login/_test_login/' allauth/socialaccount/providers/openid/tests.py
```

They can be seen by branching https://build.opensuse.org/package/show/home:jayvdb:django/python-django-allauth , and removing the hacks in the `%check` section

Log:
```console

[   54s] + django-admin-3.7 test
[   92s] ......................................................................................................................................EE.F............................................................./home/abuild/rpmbuild/BUILD/django-allauth-0.38.0/allauth/socialaccount/tests.py:82: UserWarning: Cannot test provider evernote, no oauth mock
[   92s]   % self.provider.id)
[  118s] .............................................................................................................EE.................................................................../home/abuild/rpmbuild/BUILD/django-allauth-0.38.0/allauth/socialaccount/tests.py:82: UserWarning: Cannot test provider trello, no oauth mock
[  118s]   % self.provider.id)
[  118s] ./home/abuild/rpmbuild/BUILD/django-allauth-0.38.0/allauth/socialaccount/tests.py:48: UserWarning: Cannot test provider trello, no oauth mock
[  118s]   % self.provider.id)
[  126s] .................................................................
[  126s] ======================================================================
[  126s] ERROR: test_account_refresh_token_saved_next_login (allauth.socialaccount.providers.cern.tests.CernTests)
[  126s] ----------------------------------------------------------------------
[  126s] Traceback (most recent call last):
[  126s]   File "/home/abuild/rpmbuild/BUILD/django-allauth-0.38.0/allauth/socialaccount/tests.py", line 210, in test_account_refresh_token_saved_next_login
[  126s]     self.test_account_tokens(multiple_login=True)
[  126s]   File "/home/abuild/rpmbuild/BUILD/django-allauth-0.38.0/allauth/socialaccount/tests.py", line 187, in test_account_tokens
[  126s]     provider=self.provider.id).get()
[  126s]   File "/usr/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
[  126s]     self.model._meta.object_name
[  126s] allauth.socialaccount.models.SocialAccount.DoesNotExist: SocialAccount matching query does not exist.
[  126s] 
[  126s] ======================================================================
[  126s] ERROR: test_account_tokens (allauth.socialaccount.providers.cern.tests.CernTests)
[  126s] ----------------------------------------------------------------------
[  126s] Traceback (most recent call last):
[  126s]   File "/home/abuild/rpmbuild/BUILD/django-allauth-0.38.0/allauth/socialaccount/tests.py", line 187, in test_account_tokens
[  126s]     provider=self.provider.id).get()
[  126s]   File "/usr/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
[  126s]     self.model._meta.object_name
[  126s] allauth.socialaccount.models.SocialAccount.DoesNotExist: SocialAccount matching query does not exist.
[  126s] 
[  126s] ======================================================================
[  126s] ERROR: test_login (allauth.socialaccount.providers.openid.tests.OpenIDTests)
[  126s] ----------------------------------------------------------------------
[  126s] Traceback (most recent call last):
[  126s]   File "/home/abuild/rpmbuild/BUILD/django-allauth-0.38.0/allauth/socialaccount/providers/openid/tests.py", line 29, in test_login
[  126s]     assert 'login.yahooapis' in resp['location']
[  126s]   File "/usr/lib/python3.7/site-packages/django/http/response.py", line 144, in __getitem__
[  126s]     return self._headers[header.lower()][1]
[  126s] KeyError: 'location'
[  126s] 
[  126s] ======================================================================
[  126s] ERROR: test_login_with_extra_attributes (allauth.socialaccount.providers.openid.tests.OpenIDTests)
[  126s] ----------------------------------------------------------------------
[  126s] Traceback (most recent call last):
[  126s]   File "/usr/lib/python3.7/site-packages/django/test/utils.py", line 367, in inner
[  126s]     return func(*args, **kwargs)
[  126s]   File "/home/abuild/rpmbuild/BUILD/django-allauth-0.38.0/allauth/socialaccount/providers/openid/tests.py", line 70, in test_login_with_extra_attributes
[  126s]     assert 'login.yahooapis' in resp['location']
[  126s]   File "/usr/lib/python3.7/site-packages/django/http/response.py", line 144, in __getitem__
[  126s]     return self._headers[header.lower()][1]
[  126s] KeyError: 'location'
[  126s] 
[  126s] ======================================================================
[  126s] FAIL: test_login (allauth.socialaccount.providers.cern.tests.CernTests)
[  126s] ----------------------------------------------------------------------
[  126s] Traceback (most recent call last):
[  126s]   File "/usr/lib/python3.7/site-packages/django/test/utils.py", line 367, in inner
[  126s]     return func(*args, **kwargs)
[  126s]   File "/home/abuild/rpmbuild/BUILD/django-allauth-0.38.0/allauth/socialaccount/tests.py", line 164, in test_login
[  126s]     self.assertRedirects(resp, reverse('socialaccount_signup'))
[  126s]   File "/usr/lib/python3.7/site-packages/django/test/testcases.py", line 283, in assertRedirects
[  126s]     % (response.status_code, status_code)
[  126s] AssertionError: 200 != 302 : Response didn't redirect as expected: Response code was 200 (expected 302)
[  126s] 
```

Any tips about the cause will be greatly appreciated.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2210
