### ISSUE TITLE
Unable to send confirmation emails

### ISSUE THREAD

**Issue by piraka9011** [pennersr/django-allauth#2367]
I have a basic setup of Django allauth and rest-auth. I am trying to run the basic `/rest-auth/registration` out of the box.

The configuration works locally, however, when I deploy it to my API using [Zappa](https://github.com/Miserlou/Zappa/), I am unable to do so.

When creating a new user, I get the following error (with stack trace):
```
[1570162978496] [ERROR] 2019-10-04T04:22:58.414Z c60afbf6-d74a-45f1-ae0b-d131a21b77a6 Internal Server Error: /v1/rest-auth/registration/
Traceback (most recent call last):
  File "/var/task/django/core/handlers/exception.py", line 34, in inner
  response = get_response(request)
  File "/var/task/django/core/handlers/base.py", line 115, in _get_response
  response = self.process_exception_by_middleware(e, request)
  File "/var/task/django/core/handlers/base.py", line 113, in _get_response
  response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/task/django/views/decorators/csrf.py", line 54, in wrapped_view
  return view_func(*args, **kwargs)
  File "/var/task/django/views/generic/base.py", line 71, in view
  return self.dispatch(request, *args, **kwargs)
  File "/var/task/django/utils/decorators.py", line 45, in _wrapper
  return bound_method(*args, **kwargs)
  File "/var/task/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
  return view(request, *args, **kwargs)
  File "/var/task/rest_auth/registration/views.py", line 46, in dispatch
  return super(RegisterView, self).dispatch(*args, **kwargs)
  File "/var/task/rest_framework/views.py", line 505, in dispatch
  response = self.handle_exception(exc)
  File "/var/task/rest_framework/views.py", line 465, in handle_exception
  self.raise_uncaught_exception(exc)
  File "/var/task/rest_framework/views.py", line 476, in raise_uncaught_exception
  raise exc
  File "/var/task/rest_framework/views.py", line 502, in dispatch
  response = handler(request, *args, **kwargs)
  File "/var/task/rest_framework/generics.py", line 190, in post
  return self.create(request, *args, **kwargs)
  File "/var/task/rest_auth/registration/views.py", line 65, in create
  user = self.perform_create(serializer)
  File "/var/task/rest_auth/registration/views.py", line 81, in perform_create
  None)
  File "/var/task/allauth/account/utils.py", line 181, in complete_signup
  signal_kwargs=signal_kwargs)
  File "/var/task/allauth/account/utils.py", line 141, in perform_login
  send_email_confirmation(request, user, signup=signup)
  File "/var/task/allauth/account/utils.py", line 312, in send_email_confirmation
  signup=signup)
  File "/var/task/allauth/account/models.py", line 60, in send_confirmation
  confirmation.send(request, signup=signup)
  File "/var/task/allauth/account/models.py", line 166, in send
  get_adapter(request).send_confirmation_mail(request, self, signup)
  File "/var/task/allauth/account/adapter.py", line 450, in send_confirmation_mail
  ctx)
  File "/var/task/allauth/account/adapter.py", line 137, in send_mail
  msg.send()
  File "/var/task/django/core/mail/message.py", line 291, in send
  return self.get_connection(fail_silently).send_messages([self])
  File "/var/task/django/core/mail/backends/smtp.py", line 103, in send_messages
  new_conn_created = self.open()
  File "/var/task/django/core/mail/backends/smtp.py", line 63, in open
  self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/var/lang/lib/python3.6/smtplib.py", line 1031, in __init__
  source_address)
  File "/var/lang/lib/python3.6/smtplib.py", line 251, in __init__
  (code, msg) = self.connect(host, port)
  File "/var/lang/lib/python3.6/smtplib.py", line 336, in connect
  self.sock = self._get_socket(host, port, self.timeout)
  File "/var/lang/lib/python3.6/smtplib.py", line 1037, in _get_socket
  self.source_address)
  File "/var/lang/lib/python3.6/socket.py", line 724, in create_connection
  raise err
  File "/var/lang/lib/python3.6/socket.py", line 708, in create_connection
  sock = socket(af, socktype, proto)
  File "/var/lang/lib/python3.6/socket.py", line 144, in __init__
  _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
```

Any suggestions? I tested to make sure my email settings were correct using this [tool](https://www.gmass.co/smtp-test#).

**Comment by piraka9011** [comment]
This appears to be an issue with the way Lambda/Zappa is configured in AWS.
If the Lambda is in a VPC and has no connection to the internet, then you need to configure your VPC accordingly.

https://stackoverflow.com/questions/56571314/mailing-isnt-working-in-django-aws-lambda-zappa-behind-a-vpc

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2367
