### ISSUE TITLE
VKOAuth2Adapter Error

### ISSUE THREAD

**Issue by artel1992** [pennersr/django-allauth#2530]
When I send a post request with a access_token, I get an error message

> Traceback (most recent call last):
  File "D:\D\priem\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\D\priem\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\D\priem\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\D\priem\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\D\priem\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\D\priem\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\D\priem\venv\lib\site-packages\django\views\decorators\debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "D:\D\priem\venv\lib\site-packages\rest_auth\views.py", line 49, in dispatch
    return super(LoginView, self).dispatch(*args, **kwargs)
  File "D:\D\priem\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "D:\D\priem\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\D\priem\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "D:\D\priem\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\D\priem\venv\lib\site-packages\rest_auth\views.py", line 103, in post
    self.serializer.is_valid(raise_exception=True)
  File "D:\D\priem\venv\lib\site-packages\rest_framework\serializers.py", line 234, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "D:\D\priem\venv\lib\site-packages\rest_framework\serializers.py", line 436, in run_validation
    value = self.validate(value)
  File "D:\D\priem\venv\lib\site-packages\rest_auth\registration\serializers.py", line 122, in validate
    login = self.get_social_login(adapter, app, social_token, access_token)
  File "D:\D\priem\venv\lib\site-packages\rest_auth\registration\serializers.py", line 57, in get_social_login
    social_login = adapter.complete_login(request, app, token, response=response)
  File "D:\D\priem\venv\lib\site-packages\allauth\socialaccount\providers\vk\views.py", line 43, in complete_login
    uid = kwargs['response'].get('user_id')
AttributeError: 'str' object has no attribute 'get'

[08/May/2020 09:25:35] "POST /api/vk/ HTTP/1.1" 500 138809`

I am trying to implement authorization through DRF

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2530
