### ISSUE TITLE
Keycloak Provider

### ISSUE THREAD

**Issue by JustFerry** [pennersr/django-allauth#2545]
I am having issues when I am trying to run `python manage.py migrate` after enabling the     'allauth.socialaccount.providers.keycloak' provider - without this everything worked fine. Is there a bug with this provider by any chance?

My configuration is OK.

```
Traceback (most recent call last):
  File ".../python3.7/site-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'allauth.socialaccount.providers' has no attribute 'keycloak'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File ".../lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File ".../lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File ".../lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File ".../lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File ".../lib/python3.7/site-packages/django/apps/config.py", line 136, in create
    import_module(entry)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'allauth.socialaccount.providers.keycloak'
```

**Comment by davidjspooner** [comment]
Can you post what you have for INSTALLED_APPS in your settings file?

**Comment by JustFerry** [comment]
> Can you post what you have for INSTALLED_APPS in your settings file?

```
# Application definition

INSTALLED_APPS = [
    'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # allauth:,
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.keycloak',
]
```

I checked the Python files of the library - and it turned out that the pip installation doesn't download a Keycloak folder. I cloned that folder from the GitHub - and it would work, obviously. Now I'm encountering another issue, when I login it fails to decode the JSON:


```
JSONDecodeError at /accounts/keycloak/login/callback/
Request Method: | GET

Exception Type: JSONDecodeError
Exception Value: Expecting value: line 1 column 1 (char 0)
Exception Location: /usr/lib/python3.7/json/decoder.py in raw_decode, line 355
Python version 3.7.7
```

**Comment by pennersr** [comment]
Keycloak is not released yet -- the version on pypi does not have it.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2545
