### ISSUE TITLE
ModuleNotFoundError on 0.43.0

### ISSUE THREAD

**Issue by iMerica** [pennersr/django-allauth#2714]
Hi, 

I maintain [Dj-Rest-Auth](https://github.com/jazzband/dj-rest-auth) which has an optional dependency on this package. I wanted to bring to your attention that all of our test suites pass in django-allauth==0.42.0, but fail in django-allauth==0.43.0 with the following error:

```
Traceback (most recent call last):
  File "<string>", line 3, in wrapper
  File "/Users/michael/Projects/dj-rest-auth/dj_rest_auth/tests/test_social.py", line 366, in test_social_connect
    self.post(
  File "/Users/michael/Projects/dj-rest-auth/dj_rest_auth/tests/mixins.py", line 68, in post
    return self.send_request('post', *args, **kwargs)
  File "/Users/michael/Projects/dj-rest-auth/dj_rest_auth/tests/mixins.py", line 54, in send_request
    self.response = request_func(*args, **kwargs)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/test/client.py", line 742, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/test/client.py", line 404, in post
    return self.generic('POST', path, post_data, content_type,
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/test/client.py", line 470, in generic
    return self.request(**r)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/test/client.py", line 710, in request
    self.check_exception(response)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/test/client.py", line 571, in check_exception
    raise exc_value
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Users/michael/Projects/dj-rest-auth/dj_rest_auth/registration/views.py", line 43, in dispatch
    return super(RegisterView, self).dispatch(*args, **kwargs)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/Users/michael/Projects/dj-rest-auth/dj_rest_auth/registration/views.py", line 63, in create
    user = self.perform_create(serializer)
  File "/Users/michael/Projects/dj-rest-auth/dj_rest_auth/registration/views.py", line 79, in perform_create
    complete_signup(self.request._request, user,
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/allauth/account/utils.py", line 209, in complete_signup
    return perform_login(
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/allauth/account/utils.py", line 172, in perform_login
    send_email_confirmation(request, user, signup=signup, email=email)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/allauth/account/utils.py", line 346, in send_email_confirmation
    email_address.send_confirmation(request, signup=signup)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/allauth/account/models.py", line 62, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/allauth/account/models.py", line 169, in send
    get_adapter(request).send_confirmation_mail(request, self, signup)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/allauth/account/adapter.py", line 464, in send_confirmation_mail
    self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/allauth/account/adapter.py", line 135, in send_mail
    msg = self.render_mail(template_prefix, email, context)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/allauth/account/adapter.py", line 116, in render_mail
    bodies[ext] = render_to_string(
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/template/base.py", line 168, in render
    with context.bind_template(self):
  File "/Users/michael/.pyenv/versions/3.8.0/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/template/context.py", line 240, in bind_template
    processors = (template.engine.template_context_processors +
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/template/engine.py", line 85, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/template/engine.py", line 85, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
  File "/Users/michael/Projects/dj-rest-auth/.tox/python3.9-django3/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Users/michael/.pyenv/versions/3.8.0/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django.core.context_processors'
```

Looks like this is raised when we call `complete_signup` in our registration view.

Thank you,

Michael

**Comment by pennersr** [comment]
Closing -- outdated.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2714
