### ISSUE TITLE
emails with "." before domain break signup

### ISSUE THREAD

**Issue by bb4L** [pennersr/django-allauth#2733]
If a user is correctly signed up with the email "abc@abc.ch" and a new user with "ab.c@abc.ch" tries to sign up, allauth fails with a `AssertionError`

stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/allauth/account/views.py", line 215, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/allauth/account/views.py", line 81, in dispatch
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/allauth/account/views.py", line 193, in dispatch
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/allauth/account/views.py", line 104, in post
    response = self.form_valid(form)
  File "/usr/local/lib/python3.6/site-packages/allauth/account/views.py", line 231, in form_valid
    self.user = form.save(self.request)
  File "/usr/local/lib/python3.6/site-packages/allauth/account/forms.py", line 410, in save
    setup_user_email(request, user, [])
  File "/usr/local/lib/python3.6/site-packages/allauth/account/utils.py", line 264, in setup_user_email
    assert not EmailAddress.objects.filter(user=user).exists()
AssertionError
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2733
