### ISSUE TITLE
Invalid address

### ISSUE THREAD

**Issue by nortigo** [pennersr/django-allauth#2739]
Hi,

I'm using allauth 0.44.0 with django 3.1.4. When I try to create an account with a fake email address, I got this error:

```
Internal Server Error: /en/account/signup/
Traceback (most recent call last):
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/django/core/mail/message.py", line 82, in sanitize_address
    token, rest = parser.get_mailbox(addr)
  File "/usr/lib/python3.8/email/_header_value_parser.py", line 1791, in get_mailbox
    token, value = get_name_addr(value)
  File "/usr/lib/python3.8/email/_header_value_parser.py", line 1760, in get_name_addr
    if value[0] in CFWS_LEADER:
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/allauth/account/views.py", line 230, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/allauth/account/views.py", line 74, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/allauth/account/views.py", line 204, in dispatch
    return super(CloseableSignupMixin, self).dispatch(request, *args, **kwargs)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/allauth/account/views.py", line 102, in post
    response = self.form_valid(form)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/allauth/account/views.py", line 248, in form_valid
    return complete_signup(
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/allauth/account/utils.py", line 209, in complete_signup
    return perform_login(
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/allauth/account/utils.py", line 175, in perform_login
    send_email_confirmation(request, user, signup=signup, email=email)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/allauth/account/utils.py", line 346, in send_email_confirmation
    email_address.send_confirmation(request, signup=signup)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/allauth/account/models.py", line 62, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/allauth/account/models.py", line 169, in send
    get_adapter(request).send_confirmation_mail(request, self, signup)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/allauth/account/adapter.py", line 464, in send_confirmation_mail
    self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/allauth/account/adapter.py", line 136, in send_mail
    msg.send()
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 121, in _send
    from_email = sanitize_address(email_message.from_email, encoding)
  File "/home/nortigo/projects/venvs/nortigo/lib/python3.8/site-packages/django/core/mail/message.py", line 84, in sanitize_address
    raise ValueError('Invalid address "%s"' % addr)
ValueError: Invalid address ""
```

Is there a way to catch this exception and just display an invalid address message?

**Comment by nortigo** [comment]
UPDATE: I forgot to set DEFAULT_FROM_EMAIL in my settings.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2739
