### ISSUE TITLE
SMTPRecipientsRefused at /accounts/signup/

### ISSUE THREAD

**Issue by regiov** [pennersr/django-allauth#2750]
Hi, I recently migrated a website to a different host, and now whenever a user tries to register with a wrong e-mail (Domain not found) the website crashes with status code 500:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Django-3.1.3-py3.6.egg/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/Django-3.1.3-py3.6.egg/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Django-3.1.3-py3.6.egg/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Django-3.1.3-py3.6.egg/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Django-3.1.3-py3.6.egg/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django_allauth-0.42.0-py3.6.egg/allauth/account/views.py", line 215, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django_allauth-0.42.0-py3.6.egg/allauth/account/views.py", line 81, in dispatch
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django_allauth-0.42.0-py3.6.egg/allauth/account/views.py", line 193, in dispatch
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Django-3.1.3-py3.6.egg/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django_allauth-0.42.0-py3.6.egg/allauth/account/views.py", line 104, in post
    response = self.form_valid(form)
  File "/usr/local/lib/python3.6/dist-packages/django_allauth-0.42.0-py3.6.egg/allauth/account/views.py", line 236, in form_valid
    self.get_success_url())
  File "/usr/local/lib/python3.6/dist-packages/django_allauth-0.42.0-py3.6.egg/allauth/account/utils.py", line 192, in complete_signup
    signal_kwargs=signal_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django_allauth-0.42.0-py3.6.egg/allauth/account/utils.py", line 155, in perform_login
    send_email_confirmation(request, user, signup=signup)
  File "/usr/local/lib/python3.6/dist-packages/django_allauth-0.42.0-py3.6.egg/allauth/account/utils.py", line 323, in send_email_confirmation
    signup=signup)
  File "/usr/local/lib/python3.6/dist-packages/django_allauth-0.42.0-py3.6.egg/allauth/account/models.py", line 58, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/usr/local/lib/python3.6/dist-packages/django_allauth-0.42.0-py3.6.egg/allauth/account/models.py", line 163, in send
    get_adapter(request).send_confirmation_mail(request, self, signup)
  File "/usr/local/lib/python3.6/dist-packages/django_allauth-0.42.0-py3.6.egg/allauth/account/adapter.py", line 455, in send_confirmation_mail
    ctx)
  File "/usr/local/lib/python3.6/dist-packages/django_allauth-0.42.0-py3.6.egg/allauth/account/adapter.py", line 137, in send_mail
    msg.send()
  File "/usr/local/lib/python3.6/dist-packages/Django-3.1.3-py3.6.egg/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.6/dist-packages/Django-3.1.3-py3.6.egg/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/usr/local/lib/python3.6/dist-packages/Django-3.1.3-py3.6.egg/django/core/mail/backends/smtp.py", line 125, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.6/smtplib.py", line 881, in sendmail
    raise SMTPRecipientsRefused(senderrs)

Actually, this is one of the five possible exceptions that smtplib.py can raise, and there's no catch for them across the whole code chain. Since this request is entirely managed by django-allauth, how can I avoid the crash and display a user-friendly error message? Is there a workaround?

**Comment by pennersr** [comment]
Closing -- https://github.com/pennersr/django-allauth/issues/1326#issuecomment-195528343

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2750
