### ISSUE TITLE
OSError: No translation files found for default language no-no after upgrade to 0.43.0

### ISSUE THREAD

**Issue by yhoiseth** [pennersr/django-allauth#2780]
Thank you for this project.

## Description

I ran into a problem after upgrading from 0.42.0 to 0.43.0. Running `manage.py` command now yields:

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/yngve/.pyenv/versions/3.8.7/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/yngve/.pyenv/versions/3.8.7/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/yngve/.pyenv/versions/3.8.7/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/yngve/Repositories/entrepedia/entrepedia/app/models.py", line 3, in <module>
    from django.contrib.auth.models import AbstractUser, UserManager
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/contrib/auth/models.py", line 90, in <module>
    class Group(models.Model):
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/db/models/base.py", line 161, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/db/models/fields/related.py", line 1637, in contribute_to_class
    self.remote_field.through = create_many_to_many_intermediary_model(self, cls)
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/db/models/fields/related.py", line 1099, in create_many_to_many_intermediary_model
    'verbose_name': _('%(from)s-%(to)s relationship') % {'from': from_, 'to': to},
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/utils/functional.py", line 176, in __mod__
    return str(self) % rhs
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/utils/functional.py", line 140, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 94, in gettext
    return _trans.gettext(message)
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 355, in gettext
    _default = _default or translation(settings.LANGUAGE_CODE)
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 268, in translation
    _translations[language] = DjangoTranslation(language)
  File "/Users/yngve/.pyenv/versions/3.8.7/envs/entrepedia/lib/python3.8/site-packages/django/utils/translation/trans_real.py", line 160, in __init__
    raise OSError('No translation files found for default language %s.' % settings.LANGUAGE_CODE)
OSError: No translation files found for default language no-no.
```

## Investigation

I did some digging and discovered that `allauth/locale/no/` was renamed to `allauth/locale/nb/` in [this commit](https://github.com/pennersr/django-allauth/commit/ad60cfd97d7bf38b216711f872e09deeb59549c3) by @apekatten.

(“nb” stands for “Norwegian Bokmaal”, which is one of two official dialects, the other being “nn” or “Norwegian Nynorsk”.)

Changing language in our settings from `no` to `nb` solves the problem. However, this introduces a different problem: Our site at example.com/no/ now becomes example.com/nb/. This, in turn, creates two problems:

1. Existing links to example.com/no/ break.
2. `/nb/` is less understandable for users than `/no/`. People are used to the Norwegian version of a site being under `/no/`, not `/nb/`. For example, Apple’s Norwegian site is at https://www.apple.com/no/.

## Possible solutions

Using “nb” in django-allauth’s case might be more correct than “no” because it is more specific. (The translations are written in Bokmaal.) So just changing the path back to use “no” might not be the best solution. But I’m not sure. Maybe @apekatten can comment?

Another alternative is to create a symlink from `nb` to `no`:

```
drwxr-xr-x  3 yngve  staff  96 Feb  6 09:16 nb/
drwxr-xr-x  3 yngve  staff  96 Feb  6 09:16 nl/
lrwxr-xr-x  1 yngve  staff   2 Feb  6 09:28 no@ -> nb
```

I tested this and it solves my problem. I can’t immediately see any downsides to it. I’ll try to create a PR.

**Comment by pennersr** [comment]
Closing -- perhaps it would be better to do a no->nb mapping at the url routing level.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2780
