### ISSUE TITLE
Keycloak: JSONDecodeError Internal Server - Error: /accounts/keycloak/login/callback/

### ISSUE THREAD

**Issue by surfer190** [pennersr/django-allauth#2819]
Provider: Keycloak
Django-allauth version:`django-allauth==0.44.0`
Python version: `Python 3.8.5`
Keycloak Version: `9.0.3`

Place in code error is raised (`allauth/socialaccount/providers/keycloak/views.py`): 

    def complete_login(self, request, app, token, response):
        response = requests.get(
            self.profile_url, headers={"Authorization": "Bearer " + str(token)}
        )
        response.raise_for_status()
        >>>> extra_data = response.json()

Debugging of response:

    ipdb> response
    <Response [200]>
    ipdb> response.json()
    *** json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    ipdb> response.content
    b'eyJhbGciO....'

As you can see the response is the encoded JWT.

Exception:

```
Internal Server Error: /accounts/keycloak/login/callback/
Traceback (most recent call last):
  File "~/projects/django_openidc/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "~/projects/django_openidc/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "~/projects/django_openidc/env/lib/python3.8/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 77, in view
    return self.dispatch(request, *args, **kwargs)
  File "~/projects/django_openidc/env/lib/python3.8/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 136, in dispatch
    login = self.adapter.complete_login(
  File "~/projects/django_openidc/env/lib/python3.8/site-packages/allauth/socialaccount/providers/keycloak/views.py", line 32, in complete_login
    extra_data = response.json()
  File "~/projects/django_openidc/env/lib/python3.8/site-packages/requests/models.py", line 889, in json
    return complexjson.loads(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by surfer190** [comment]
A setting on the identity provider side was signing the user info endpoint.

The `Userinfo signed response algorithm` must be unsigned. User `Fine Grain OpenID Connect Configuration` on the client.

<img width="781" alt="keycloak-userinfo-signed-response-algorithm" src="https://user-images.githubusercontent.com/3285222/112957226-85493000-9141-11eb-8680-d9b64409e530.png">

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2819
