### ISSUE TITLE
How to test registration with activation

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#2833]
How can I test the activation of a user?

This is my approach so far. I can register, but activation is failing.

```
    def test_registration_form_valid_registration_and_login(self):
        ###Register
        email       = 'test@test.com'
        password    = '123123123'
        client = Client()
        data    = {
            'email': email,
            'password1': password
        }
        response = client.post(
            '/accounts/signup/',
            data
        )
        self.assertEqual(User.objects.all().count(), 1)

        ###Activate user
        emailaddress = User.objects.get(email=email).emailaddress_set.first()

        emailconfirmation   = EmailConfirmation.create(emailaddress)
        key                 = emailconfirmation.key
        response            = client.get('/accounts/confirm-email/' + str(key)+ '/')

        self.assertEqual(response.status_code, 200)
        soup                = BeautifulSoup(response.content, 'html.parser')
        form_url            = soup.form['action']
        response            = client.post(form_url) # <-- Fails here
```

The last step is failing with this error:

```
Traceback (most recent call last):
  File "/home/user/git/myproject/source/myproject/myallauth/tests.py", line 99, in test_registration_form_valid_registration_and_login
    response            = client.post(form_url)
  File "/home/user/git/myvenv/lib/python3.7/site-packages/django/test/client.py", line 543, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/home/user/git/myvenv/lib/python3.7/site-packages/django/test/client.py", line 357, in post
    secure=secure, **extra)
  File "/home/user/git/myvenv/lib/python3.7/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/home/user/git/myvenv/lib/python3.7/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/home/user/git/myvenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/user/git/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/user/git/myvenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/git/myvenv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/git/myvenv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/git/myvenv/lib/python3.7/site-packages/allauth/account/views.py", line 280, in post
    confirmation.confirm(self.request)
  File "/home/user/git/myvenv/lib/python3.7/site-packages/allauth/account/models.py", line 111, in confirm
    if not self.key_expired() and not self.email_address.verified:
  File "/home/user/git/myvenv/lib/python3.7/site-packages/allauth/account/models.py", line 105, in key_expired
    + datetime.timedelta(days=app_settings
TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'
```

What I am missing?

**Comment by sowinski** [comment]
Solved the problem a second after posting this. I found in your test this line of code before you send the POST request.

`EmailConfirmation.objects.update(sent=now() - timedelta(days=1))`

This helps. But I do not really understand why this is neccesery?

**Comment by 9mido** [comment]
@sowinski Can you provide your code solution to help others? It seems that line of code has to do with the cooldown setting allauth uses. But I am not exactly sure since I prefer the timeout PR that still has yet to be merged.

**Comment by sowinski** [comment]
@9mido Sorry, I haven't seen your message.

That's how I do it now.

```
        # User is not activated yes
        emailaddress = User.objects.get(email=email).emailaddress_set.first()
        self.assertEqual(emailaddress.verified, False)
```
I do the following steps to activate the user programticaly
```

        #here i get the key and call it with the help of django client
        emailaddress        = User.objects.get(email=email).emailaddress_set.first()
        emailconfirmation   = EmailConfirmation.create(emailaddress)
        key                 = emailconfirmation.key
        response            = client.get('/accounts/confirm-email/' + str(key)+ '/')
        soup                = BeautifulSoup(response.content, 'html.parser')
        form_url            = soup.form['action']
        EmailConfirmation.objects.update(sent=now() - timedelta(days=1)) #<-- Here you have to set the time back to yesterday ( one second is enough)
        #afterwards you can activate the user through this post call
        response            = client.post(form_url, follow=True)
        emailaddress = User.objects.get(email=email).emailaddress_set.first()
        self.assertEqual(emailaddress.verified, True)
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2833
