### ISSUE TITLE
Default AddEmailForm ignores ACCOUNT_EMAIL_VERIFICATION setting and attempts to send email, resulting in OSError at /accounts/email/

### ISSUE THREAD

**Issue by lorey** [pennersr/django-allauth#2876]
So, this might be an issue/misunderstanding on my side, but maybe it's not:

I'm running a basic Django setup without much custom configuration/settings, esp. no email set-up so far. I'm using allauth with the default configuration. Since I haven't configured email yet, I can't send verification emails and have thus set `ACCOUNT_EMAIL_VERIFICATION = "none"`. It seems that allauth tries to send an email anyhow.

## Expected behavior
With `ACCOUNT_EMAIL_VERIFICATION = "none"` I would expect no verification attempt as the documentation states:
> When set to “mandatory” the user is blocked from logging in until the email address is verified. Choose “optional” or “none” to allow logins with an unverified e-mail address. In case of “optional”, the e-mail verification mail is still sent, whereas in case of “none” no e-mail verification mails are sent.

## Observed behaviour
When adding an email to my account with the default view, I get the following exception:
```
Environment:


Request Method: POST
Request URL: http://localhost:8008/accounts/email/

Django Version: 3.2.3
Python Version: 3.8.10
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'crispy_forms',
 'networking_public',
 'networking_base',
 'networking_web',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.google']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/allauth/account/views.py", line 419, in dispatch
    return super(EmailView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/allauth/account/views.py", line 445, in post
    res = super(EmailView, self).post(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/allauth/account/views.py", line 102, in post
    response = self.form_valid(form)
  File "/usr/local/lib/python3.8/site-packages/allauth/account/views.py", line 427, in form_valid
    email_address = form.save(self.request)
  File "/usr/local/lib/python3.8/site-packages/allauth/account/forms.py", line 469, in save
    return EmailAddress.objects.add_email(
  File "/usr/local/lib/python3.8/site-packages/allauth/account/managers.py", line 24, in add_email
    email_address.send_confirmation(request, signup=signup)
  File "/usr/local/lib/python3.8/site-packages/allauth/account/models.py", line 62, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/usr/local/lib/python3.8/site-packages/allauth/account/models.py", line 169, in send
    get_adapter(request).send_confirmation_mail(request, self, signup)
  File "/usr/local/lib/python3.8/site-packages/allauth/account/adapter.py", line 464, in send_confirmation_mail
    self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
  File "/usr/local/lib/python3.8/site-packages/allauth/account/adapter.py", line 136, in send_mail
    msg.send()
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 62, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)

Exception Type: OSError at /accounts/email/
Exception Value: [Errno 99] Cannot assign requested address
```

To me, this looks like a verification email is being sent anyway which fails due to a failing connection to a default email host (`localhost:25`) I haven't set up. 

With a little bit of digging I found the following:
When saving the email, `AddEmailForm` sets `confirm=True` resulting in the observed attempt to send a verification email. See https://github.com/pennersr/django-allauth/blob/0.44.0/allauth/account/forms.py#L470

Again, I would expect no attempt to send a verification email as stated in the documentation.

Let me know if this is right or wrong. Would try to fix this, either by extending the docs or the Form class. Thanks!

**Comment by lorey** [comment]
## Quick fix
Maybe this helps someone looking for a quick fix.

settings.py
```
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_FORMS = {
   # replace the default form
    "add_email": "[your package].forms.AddEmailFormRespectingVerification"
}
```

forms.py
```
import django.conf
from allauth.account.forms import AddEmailForm
from allauth.account.models import EmailAddress


class AddEmailFormRespectingVerification(AddEmailForm):
    """
    This is the default AddEmailForm with the only difference
    being that it sends no verification email if ACCOUNT_EMAIL_VERIFICATION is 'none'.
    """

    def save(self, request):
        confirm = django.conf.settings.ACCOUNT_EMAIL_VERIFICATION != "none"
        return EmailAddress.objects.add_email(
            request, self.user, self.cleaned_data["email"], confirm=confirm
        )

```

**Comment by lorey** [comment]
Seems to be a misunderstanding on my side. I thought the setting in generic and applies for all email verficiations, it's only explicit for _signup_ though. See #2896.

Docs state:
> Determines the e-mail verification method during signup 

I would argue that expected behavior is to not verify _all_ emails, but that's up for debate...

**Comment by pennersr** [comment]
This settings is documented as:

> ACCOUNT_EMAIL_VERIFICATION (="optional")
>   Determines the e-mail verification method **during signup**...

You are POST'ing to `accounts/email/` -- that is not signing up.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2876
