### ISSUE TITLE
使用百度登录有异常 KeyError: 'uid'

### ISSUE THREAD

**Issue by AniPython** [pennersr/django-allauth#2943]
错误信息:
[2021-09-04 15:13:07,725] log: ERROR - Internal Server Error: /accounts/baidu/login/callback/
Traceback (most recent call last):
  File "/home/pyenv/ani/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/pyenv/ani/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pyenv/ani/lib/python3.9/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 77, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pyenv/ani/lib/python3.9/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 136, in dispatch
    login = self.adapter.complete_login(
  File "/home/pyenv/ani/lib/python3.9/site-packages/allauth/socialaccount/providers/baidu/views.py", line 23, in complete_login
    return self.get_provider().sociallogin_from_response(request, extra_data)
  File "/home/pyenv/ani/lib/python3.9/site-packages/allauth/socialaccount/providers/base.py", line 83, in sociallogin_from_response
    uid = self.extract_uid(response)
  File "/home/pyenv/ani/lib/python3.9/site-packages/allauth/socialaccount/providers/baidu/provider.py", line 26, in extract_uid
    return data["uid"]
KeyError: 'uid'

**Comment by pennersr** [comment]
Insufficient info, closing

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2943
