### ISSUE TITLE
Unable to test the Register view by overriding djagno settings

### ISSUE THREAD

**Issue by g-kartik** [pennersr/django-allauth#3000]
I tried to test the response of register view when email verification is turned on. But by overriding the settings in the test method I get the following error. But if I hardcode this setting in the settings file, the test runs successfully. It seems all-auth is not referring to the overridden settings

![image](https://user-images.githubusercontent.com/83916067/147413772-cd1bf118-1164-49e0-accd-366a2d2d7bd8.png)

Error
Traceback (most recent call last):
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/mnt/Storage 2/cvat/cvat/apps/iam/tests/test_rest_api.py", line 33, in test_register_account_with_email_verification
    response = self.client.post(url, data, format='json')
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/rest_framework/test.py", line 295, in post
    response = super().post(
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/rest_framework/test.py", line 209, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/rest_framework/test.py", line 233, in generic
    return super().generic(
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/rest_framework/test.py", line 285, in request
    return super().request(**kwargs)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/rest_framework/test.py", line 237, in request
    request = super().request(**kwargs)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/rest_auth/registration/views.py", line 46, in dispatch
    return super(RegisterView, self).dispatch(*args, **kwargs)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/rest_auth/registration/views.py", line 65, in create
    user = self.perform_create(serializer)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/rest_auth/registration/views.py", line 79, in perform_create
    complete_signup(self.request._request, user,
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/allauth/account/utils.py", line 209, in complete_signup
    return perform_login(
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/allauth/account/utils.py", line 175, in perform_login
    send_email_confirmation(request, user, signup=signup, email=email)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/allauth/account/utils.py", line 346, in send_email_confirmation
    email_address.send_confirmation(request, signup=signup)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/allauth/account/models.py", line 62, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/allauth/account/models.py", line 169, in send
    get_adapter(request).send_confirmation_mail(request, self, signup)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/allauth/account/adapter.py", line 453, in send_confirmation_mail
    activate_url = self.get_email_confirmation_url(request, emailconfirmation)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/allauth/account/adapter.py", line 447, in get_email_confirmation_url
    url = reverse("account_confirm_email", args=[emailconfirmation.key])
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/mnt/Storage 2/cvat/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'account_confirm_email' not found. 'account_confirm_email' is not a valid view function or pattern name.

Destroying test database for alias 'default'...

Process finished with exit code 1

**Comment by g-kartik** [comment]
Any solutions?

**Comment by pennersr** [comment]
When filing issues please make sure to demonstrate an issue using just allauth. The stack trace shows `rest_framework` is involved, making this difficult to reproduce as it is likely something project specific. Hence, I have to close this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3000
