### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'method'

### ISSUE THREAD

**Issue by 9mido** [pennersr/django-allauth#3002]
When I try to login with the newest github version of allauth (not PyPi), I am hit with this error message. 

```
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/views/decorators/debug.py", line 90, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/allauth/account/views.py", line 149, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/allauth/account/views.py", line 77, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/allauth/account/views.py", line 104, in post
    if form.is_valid():
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/forms/forms.py", line 190, in is_valid
    return self.is_bound and not self.errors
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/forms/forms.py", line 185, in errors
    self.full_clean()
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/forms/forms.py", line 405, in full_clean
    self._clean_form()
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/django/forms/forms.py", line 426, in _clean_form
    cleaned_data = self.clean()
  File "/home/name/video-membership-master/courses/forms.py", line 384, in clean
    super().clean()
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/allauth/account/forms.py", line 178, in clean
    user = get_adapter(self.request).authenticate(self.request, **credentials)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/allauth/account/adapter.py", line 523, in authenticate
    self.pre_authenticate(request, **credentials)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/allauth/account/adapter.py", line 508, in pre_authenticate
    if not ratelimit.consume(
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/allauth/ratelimit.py", line 56, in consume
    if request.method == "GET" or not amount or not duration:
AttributeError: 'NoneType' object has no attribute 'method'
```

**Comment by banagale** [comment]
I'm also getting this error. It was triggered in my tests, but I also have it happening when there is a failed login. 

It appears that the post is not making it to `allauth.account.adapter.authenticate`. 

I override the `LoginView` and the `LoginForm` and use a custom adapter. Presumably, something has changed about the base versions of these that is causing the request to not be passed along.

One other thing I noticed was that the `action` searched for was `login_failed` which is not a part of the default `ACCOUNT_RATE_LIMITS` setting. Probably unrelated. But presumably this should be a part of the defaults.

Don't have time to chase this down at the moment so will be downgrading.

Are you using a custom adapter or overriding the login behavior?

**Comment by pennersr** [comment]
I am a bit confused by the stacktrace:

```
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/allauth/account/adapter.py", line 523, in authenticate
    self.pre_authenticate(request, **credentials)
  File "/home/name/.local/share/virtualenvs/project_name/lib/python3.8/site-packages/allauth/account/adapter.py", line 508, in pre_authenticate
```

These line numbers don't seem to match allauth 0.48.0. E.g. line 508 of `adapter.py` is not in `pre_authenticate` ?

**Comment by pennersr** [comment]
> It appears that the post's request is not making it to allauth.account.adapter.authenticate.

There is exactly one call to `authenticate()` in allauth:
```
File: allauth/account/forms.py
 178  41         user = get_adapter(self.request).authenticate(self.request, **credentials)
```
The `request` is definitely passed there. Possibly, you're not passing `request` in your custom login view/form. Previously, this may have worked as `request` was perhaps unused in your flows. Whereas now, with rate limits by default enabled, we need `request`.

**Comment by banagale** [comment]
@pennersr Thank you for that feedback, it was helpful in diagnosing this.

You are correct that I was not passing `request` in my custom form. 

I haven't touched this form since July 2020. I think I modified the `__init__` to add custom class attributes and `autocomplete`, `autofocus`, etc. My `__init__` leaves out older logic but I think it was still prior to [this change](https://github.com/pennersr/django-allauth/commit/239a72352df97509631774502981991cf6c1c325).

Anyhow, it looks like I carried along the `self.request = kwargs.pop('request', None)` at the start of that init.  So when I call the `super(MyLoginForm, self).__init__(*args, **kwargs)` the request has been popped off or removed.

Here's the code I had:

```
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(MyLoginForm, self).__init__(*args, **kwargs)
        login_widget = forms.TextInput(
            attrs={'type': 'email', 'class': 'form-control form-control-lg', 'placeholder': 'Email Address',
                   'autocomplete': 'username', 'autofocus': 'autofocus', 'autocorrect': 'off',
                   'autocapitalize': 'off'}
        )
        login_field = forms.EmailField(label="E-mail",
                                       widget=login_widget)

        self.fields["login"] = login_field
        set_form_field_order(self, ["login", "password", "remember"])
```
You're also correct that request was not getting further used in my customized flow.

When I commented out / removed the popping of the request argument in my form's init, my tests passed and login worked again just fine.

**Comment by some1ataplace** [comment]
Just as the original author of this issue, here is my custom login code that produces the same error.

```
class CaptchaLoginForm(LoginForm): 

    if settings.RECAPTCHA_ENABLED == '1':
        recaptcha_token = forms.CharField(required=True)

        def clean(self):
            super().clean()
            credentials = self.user_credentials()
            user = get_adapter(self.request).authenticate(self.request, **credentials)
            email = user.email
            if EmailAddress.objects.filter(email=email, verified=False).exists() is True:
                raise forms.ValidationError('Please check ' + email + ' to verify your email address.')

            url = 'https://www.google.com/recaptcha/api/siteverify'
            params = {
                'secret': settings.CAPTCHA_PRIVATE_KEY,
                'response': self.cleaned_data['recaptcha_token']
            }

            response = requests.post(url, params)
            if response.status_code == requests.codes.ok:
                print('recaptcha')
                if response.json()['success'] and response.json()['action'] == '/accounts/login/':
                    pass
                else:
                    raise forms.ValidationError('ReCAPTCHA is invalid.')
            else:
                pass

            return self.cleaned_data

    field_order = ['username', 'password', 'captcha',]
    def __init__(self, request, *args, **kwargs):
        super(CaptchaLoginForm, self).__init__(*args, **kwargs)
        self.fields['login'] = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Username or E-mail', 'autocomplete':'off'}), label='Username or E-mail', required=True)
        self.helper = FormHelper()
    pass
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3002
