### ISSUE TITLE
Problem with Facebook Provider (Django 4.0.1) - from django.utils.http import urlquote

### ISSUE THREAD

**Issue by sannjayy** [pennersr/django-allauth#3006]
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Sanjay\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Sanjay\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\django\core\management\commands\runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\django\core\management\base.py", line 438, in check
    all_issues = checks.run_checks(
  File "E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\django\core\checks\registry.py", line 77, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\django\urls\resolvers.py", line 446, in check
    for pattern in self.url_patterns:
  File "E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\django\urls\resolvers.py", line 632, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\django\urls\resolvers.py", line 625, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Sanjay\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:\Learning Me\Rest Framework\drf-all-auth\project\urls.py", line 41, in <module>
    path('account/', include('accounts.urls')),
  File "E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\Sanjay\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:\Learning Me\Rest Framework\drf-all-auth\accounts\urls.py", line 3, in <module>
    from .views import GoogleLogin
  File "E:\Learning Me\Rest Framework\drf-all-auth\accounts\views.py", line 8, in <module>
    from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter
  File "E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\allauth\socialaccount\providers\facebook\views.py", line 22, in <module>
    from .provider import GRAPH_API_URL, GRAPH_API_VERSION, FacebookProvider
  File "E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\allauth\socialaccount\providers\facebook\provider.py", line 11, in <module>
    from django.utils.http import urlquote
ImportError: cannot import name 'urlquote' from 'django.utils.http' (E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\django\utils\http.py)

**Comment by Tobeyforce** [comment]
Seems like 4.0 broke compatability with the facebook provider due to urlquote.

Seems like urlquote was deprecated in django 4.0:
https://docs.djangoproject.com/en/4.0/releases/4.0/

> "django.utils.http.urlquote(), urlquote_plus(), urlunquote(), and urlunquote_plus() are removed."

Any suggestions on an alternative? Should exist a relatively easy fix to apply in the meantime?

**Comment by Tobeyforce** [comment]
Looking at the django source code it seems its been replaced by urllib.parse.quote()
I might attempt to create a PR for it.

>   'django.utils.http.urlquote() is deprecated in favor of '
>         'urllib.parse.quote().',

**Comment by Franks20Ac** [comment]
> Looking at the django source code it seems its been replaced by urllib.parse.quote() Looks like it might've been fixed in newer versions of allauth though?
> 
> > 'django.utils.http.urlquote() is deprecated in favor of '
> > 'urllib.parse.quote().',

This worked for me, thanks. Using Windows:
Replace in YOUR_VENV/Lib/site-packages/social_django/middleware.py
from django.utils.http import urlquote
to
from urllib.parse import quote

In your case the chance is probably in 'E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\django\utils\http.py'.

Remember that the change is also made on each call of the function. In my case it was only once in 'process_exception'.

**Comment by zelhus-iliyas** [comment]
> > Looking at the django source code it seems its been replaced by urllib.parse.quote() Looks like it might've been fixed in newer versions of allauth though?
> > > 'django.utils.http.urlquote() is deprecated in favor of '
> > > 'urllib.parse.quote().',
> 
> This worked for me, thanks. Using Windows: Replace in YOUR_VENV/Lib/site-packages/social_django/middleware.py from django.utils.http import urlquote to from urllib.parse import quote
> 
> In your case the chance is probably in 'E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\django\utils\http.py'.
> 
> Remember that the change is also made on each call of the function. In my case it was only once in 'process_exception'.
> 
> PS: It could also be on this route, I'm not sure. 'E:\Learning Me\Rest Framework\drf-all-auth\zenv\lib\site-packages\allauth\socialaccount\providers\facebook\provider.py'

what will you do if we should use in production?

**Comment by t2lt** [comment]
> what will you do if we should use in production?

Try in settings.py:

from urllib.parse import urlparse
django.utils.http.urlquote = urlparse

**Comment by GusarovArtem** [comment]
if issue persists next 

locate your _site-packages/social_django/middleware.py_
you can use: `locate site-packages/social_django/middleware.py`

then change import from:
`from django.utils.http import urlquote`
to:
`from urllib.parse import quote`

do not forget to change `urlquote` to `quote` in code everywhere in that file

**Comment by pennersr** [comment]
Closing -- this is not an issue in allauth

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3006
