### ISSUE TITLE
[BUG] django-allauth is incompatible with setuptools >= 61

### ISSUE THREAD

**Issue by inhumantsar** [pennersr/django-allauth#3063]
```
Collecting django-allauth==0.41.0
  Using cached django-allauth-0.41.0.tar.gz (545 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-86d0zlwu/django-allauth_c731da7f[50](https://github.com/newton-crypto/newton/runs/5683055489?check_suite_focus=true#step:10:50)d142c198bc03[58](https://github.com/newton-crypto/newton/runs/5683055489?check_suite_focus=true#step:10:58)15afac95/setup.py", line 8, in <module>
          from setuptools import convert_path, find_packages, setup
      ImportError: cannot import name 'convert_path' from 'setuptools' (/root/.pyenv/versions/3.8.2/envs/refs_pull_3070_merge/lib/python3.8/site-packages/setuptools/__init__.py)
      [end of output]
```

Downgrading to setuptools to 60.10.0 resolves the issue

**Comment by pennersr** [comment]
Closed via e91b89fe

**Comment by pennersr** [comment]
@celinemol That is to be expected, 0.44.0 is from 2020 -- it is not fixed.

**Comment by Tiwari1812** [comment]
> @celinemol That is to be expected, 0.44.0 is from 2020 -- it is not fixed. Version 0.50.0 contains the fix.

so is there any solution?

**Comment by Tiwari1812** [comment]
> django-allauth

run: |
        pip install --upgrade pip setuptools==60.10.0 wheel
doing this but not able to get any result

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3063
