### ISSUE TITLE
Build error with Django 4.0.3

### ISSUE THREAD

**Issue by shacker** [pennersr/django-allauth#3064]
Building a project through GitHub Actions with Django 4.0.3 and allauth 0.49.0, we're crashing in the dependency stage with 

```
2022-03-25T00:07:50.7266550Z Collecting django-allauth==0.49.0
2022-03-25T00:07:50.7380557Z   Downloading django-allauth-0.49.0.tar.gz (702 kB)
2022-03-25T00:07:50.7511510Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 702.3/702.3 KB 73.7 MB/s eta 0:00:00
2022-03-25T00:07:51.0296305Z   Preparing metadata (setup.py): started
2022-03-25T00:07:51.2515406Z   Preparing metadata (setup.py): finished with status 'error'
2022-03-25T00:07:51.2590560Z   error: subprocess-exited-with-error
2022-03-25T00:07:51.2591092Z   
2022-03-25T00:07:51.2591971Z   × python setup.py egg_info did not run successfully.
2022-03-25T00:07:51.2592575Z   │ exit code: 1
2022-03-25T00:07:51.2593317Z   ╰─> [6 lines of output]
2022-03-25T00:07:51.2593814Z       Traceback (most recent call last):
2022-03-25T00:07:51.2603111Z         File "<string>", line 2, in <module>
2022-03-25T00:07:51.2604488Z         File "<pip-setuptools-caller>", line 34, in <module>
2022-03-25T00:07:51.2605834Z         File "/tmp/pip-install-nctuxiwm/django-allauth_b6df68d30bf2478ca8689694cb28655f/setup.py", line 9, in <module>
2022-03-25T00:07:51.2606547Z           from setuptools import convert_path, find_packages, setup
2022-03-25T00:07:51.2607794Z       ImportError: cannot import name 'convert_path' from 'setuptools' (/home/runner/work/greenhouse/greenhouse/.venv/lib/python3.9/site-packages/setuptools/__init__.py)
2022-03-25T00:07:51.2608469Z       [end of output]
2022-03-25T00:07:51.2609117Z   
2022-03-25T00:07:51.2609650Z   note: This error originates from a subprocess, and is likely not a problem with pip.
2022-03-25T00:07:51.2617517Z error: metadata-generation-failed
2022-03-25T00:07:51.2617931Z 
2022-03-25T00:07:51.2618609Z × Encountered error while generating package metadata.
2022-03-25T00:07:51.2619267Z ╰─> See above for output.
``

Anyone else seeing this?

**Comment by emripka** [comment]
Same error with:
- `Django==3.1.14`
- `django-allauth==0.41.0`

**Comment by celinemol** [comment]
Same with building our package with docker:
- `django==3.1.6`
- `django-allauth==0.44.0`

```
#10 17.62 Collecting django-allauth==0.44.0
#10 17.68   Downloading django-allauth-0.44.0.tar.gz (572 kB)
#10 17.70      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.5/572.5 KB 25.5 MB/s eta 0:00:00
#10 17.93   Preparing metadata (setup.py): started
#10 18.02   Preparing metadata (setup.py): finished with status 'error'
#10 18.03   error: subprocess-exited-with-error
#10 18.03   
#10 18.03   × python setup.py egg_info did not run successfully.
#10 18.03   │ exit code: 1
#10 18.03   ╰─> [6 lines of output]
#10 18.03       Traceback (most recent call last):
#10 18.03         File "<string>", line 2, in <module>
#10 18.03         File "<pip-setuptools-caller>", line 34, in <module>
#10 18.03         File "/tmp/pip-install-tv1pfme2/django-allauth_6b48ddd4ef764baca7c61240052e6cb8/setup.py", line 9, in <module>
#10 18.03           from setuptools import convert_path, find_packages, setup
#10 18.03       ImportError: cannot import name 'convert_path' from 'setuptools' (/env/lib/python3.9/site-packages/setuptools/__init__.py)
#10 18.03       [end of output]
#10 18.03   
#10 18.03   note: This error originates from a subprocess, and is likely not a problem with pip.
#10 18.03 error: metadata-generation-failed
#10 18.03 
#10 18.03 × Encountered error while generating package metadata.
#10 18.03 ╰─> See above for output.
#10 18.03 
#10 18.03 note: This is an issue with the package mentioned above, not pip.
#10 18.03 hint: See above for details.
```

**Comment by carlhodder** [comment]
Same here with 3.2, and I'm not sure what's going on.
Have a running docker instance built 3 days ago with:

- `django==3.2.3`
- `django-allauth==0.44.0`
- `setuptools==60.10.0`
- `pip==22.0.4`
- `python==3.9.11`

I've tried fixing to these versions, tried the latest versions, and a few random permutations without success. Tried rolling python 3.9.12 back to 3.9.11, all no dice.

**Comment by pennersr** [comment]
This is due to: https://github.com/pennersr/django-allauth/issues/3063

**Comment by Tiwari1812** [comment]
> Building a project through GitHub Actions with Django 4.0.3 and allauth 0.49.0, we're crashing in the dependency stage with
> 
> ```
> 2022-03-25T00:07:50.7266550Z Collecting django-allauth==0.49.0
> 2022-03-25T00:07:50.7380557Z   Downloading django-allauth-0.49.0.tar.gz (702 kB)
> 2022-03-25T00:07:50.7511510Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 702.3/702.3 KB 73.7 MB/s eta 0:00:00
> 2022-03-25T00:07:51.0296305Z   Preparing metadata (setup.py): started
> 2022-03-25T00:07:51.2515406Z   Preparing metadata (setup.py): finished with status 'error'
> 2022-03-25T00:07:51.2590560Z   error: subprocess-exited-with-error
> 2022-03-25T00:07:51.2591092Z   
> 2022-03-25T00:07:51.2591971Z   × python setup.py egg_info did not run successfully.
> 2022-03-25T00:07:51.2592575Z   │ exit code: 1
> 2022-03-25T00:07:51.2593317Z   ╰─> [6 lines of output]
> 2022-03-25T00:07:51.2593814Z       Traceback (most recent call last):
> 2022-03-25T00:07:51.2603111Z         File "<string>", line 2, in <module>
> 2022-03-25T00:07:51.2604488Z         File "<pip-setuptools-caller>", line 34, in <module>
> 2022-03-25T00:07:51.2605834Z         File "/tmp/pip-install-nctuxiwm/django-allauth_b6df68d30bf2478ca8689694cb28655f/setup.py", line 9, in <module>
> 2022-03-25T00:07:51.2606547Z           from setuptools import convert_path, find_packages, setup
> 2022-03-25T00:07:51.2607794Z       ImportError: cannot import name 'convert_path' from 'setuptools' (/home/runner/work/greenhouse/greenhouse/.venv/lib/python3.9/site-packages/setuptools/__init__.py)
> 2022-03-25T00:07:51.2608469Z       [end of output]
> 2022-03-25T00:07:51.2609117Z   
> 2022-03-25T00:07:51.2609650Z   note: This error originates from a subprocess, and is likely not a problem with pip.
> 2022-03-25T00:07:51.2617517Z error: metadata-generation-failed
> 2022-03-25T00:07:51.2617931Z 
> 2022-03-25T00:07:51.2618609Z × Encountered error while generating package metadata.
> 2022-03-25T00:07:51.2619267Z ╰─> See above for output.
> ``
> 
> Anyone else seeing this?
> ```

did you get any solution?

**Comment by pennersr** [comment]
@Tiwari1812 https://github.com/pennersr/django-allauth/issues/3064#issuecomment-1078708087

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3064
