### ISSUE TITLE
Throwing Exception for ID_TOKEN Google OAuth 

### ISSUE THREAD

**Issue by abhibhaw** [pennersr/django-allauth#3244]
```
api-api-1  | Internal Server Error: /core/auth/google/
api-api-1  | Traceback (most recent call last):
api-api-1  |   File "/py/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
api-api-1  |     response = get_response(request)
api-api-1  |                ^^^^^^^^^^^^^^^^^^^^^
api-api-1  |   File "/py/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
api-api-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
api-api-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-api-1  |   File "/py/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
api-api-1  |     return view_func(*args, **kwargs)
api-api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
api-api-1  |   File "/py/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
api-api-1  |     return self.dispatch(request, *args, **kwargs)
api-api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-api-1  |   File "/py/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
api-api-1  |     return bound_method(*args, **kwargs)
api-api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-api-1  |   File "/py/lib/python3.11/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
api-api-1  |     return view(request, *args, **kwargs)
api-api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-api-1  |   File "/py/lib/python3.11/site-packages/dj_rest_auth/views.py", line 53, in dispatch
api-api-1  |     return super().dispatch(*args, **kwargs)
api-api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-api-1  |   File "/py/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
api-api-1  |     response = self.handle_exception(exc)
api-api-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
api-api-1  |   File "/py/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
api-api-1  |     self.raise_uncaught_exception(exc)
api-api-1  |   File "/py/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
api-api-1  |     raise exc
api-api-1  |   File "/py/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
api-api-1  |     response = handler(request, *args, **kwargs)
api-api-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-api-1  |   File "/py/lib/python3.11/site-packages/dj_rest_auth/views.py", line 130, in post
api-api-1  |     self.serializer.is_valid(raise_exception=True)
api-api-1  |   File "/py/lib/python3.11/site-packages/rest_framework/serializers.py", line 227, in is_valid
api-api-1  |     self._validated_data = self.run_validation(self.initial_data)
api-api-1  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-api-1  |   File "/py/lib/python3.11/site-packages/rest_framework/serializers.py", line 429, in run_validation
api-api-1  |     value = self.validate(value)
api-api-1  |             ^^^^^^^^^^^^^^^^^^^^
api-api-1  |   File "/py/lib/python3.11/site-packages/dj_rest_auth/registration/serializers.py", line 150, in validate
api-api-1  |     login = self.get_social_login(adapter, app, social_token, token)
api-api-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-api-1  |   File "/py/lib/python3.11/site-packages/dj_rest_auth/registration/serializers.py", line 60, in get_social_login
api-api-1  |     social_login = adapter.complete_login(request, app, token, response=response)
api-api-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-api-1  |   File "/py/lib/python3.11/site-packages/allauth/socialaccount/providers/google/views.py", line 22, in complete_login
api-api-1  |     response["id_token"],
```

Getting this random error while itegrationg django-allauth and dj-rest-auth. Tried documentation and everything not sure what's going wrong.

**Comment by abhibhaw** [comment]
Found a solution https://github.com/iMerica/dj-rest-auth/issues/465

**Comment by toniengelhardt** [comment]
@abhibhaw what's the solution, downgrading allauth to `0.51.0` ?

**Comment by abhibhaw** [comment]
For now yes @toniengelhardt

**Comment by toniengelhardt** [comment]
@abhibhaw do you by chance know if this is resolved in `0.53.1` ?

**Comment by abhibhaw** [comment]
Nope @toniengelhardt

**Comment by toniengelhardt** [comment]
> Nope @toniengelhardt 

Is that a "I don't know" nope or a "It's not resolved" nope? 🤔

**Comment by abhibhaw** [comment]
> > Nope @toniengelhardt
> 
> Is that a "I don't know" nope or a "It's not resolved" nope? 🤔

Not sure one 😄

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3244
