### ISSUE TITLE
Google provider error response["id_token"], TypeError: string indices must be integers

### ISSUE THREAD

**Issue by 5no0p** [pennersr/django-allauth#3253]
I get this error when try to log in with google:

```
Internal Server Error: /users/social/google/
Traceback (most recent call last):
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\asgiref\sync.py", line 486, in thread_handler     
    raise exc_info[1]
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\django\core\handlers\exception.py", line 38, in inner
    response = await get_response(request)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\django\core\handlers\base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\asgiref\sync.py", line 448, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\users\mmoaa\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 442, in wait_for
    return await fut
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\asgiref\current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\asgiref\sync.py", line 490, in thread_handler     
    return func(*args, **kwargs)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\django\views\generic\base.py", line 70, in view   
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper 
    return bound_method(*args, **kwargs)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\django\views\decorators\debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\dj_rest_auth\views.py", line 53, in dispatch      
    return super().dispatch(*args, **kwargs)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\rest_framework\views.py", line 509, in dispatch   
    response = self.handle_exception(exc)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\rest_framework\views.py", line 506, in dispatch   
    response = handler(request, *args, **kwargs)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\dj_rest_auth\views.py", line 130, in post
    self.serializer.is_valid(raise_exception=True)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\rest_framework\serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\dj_rest_auth\registration\serializers.py", line 150, in validate
    login = self.get_social_login(adapter, app, social_token, token)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\dj_rest_auth\registration\serializers.py", line 60, in get_social_login
    social_login = adapter.complete_login(request, app, token, response=response)
  File "C:\Users\mmoaa\.virtualenvs\Django-Celery-sT3nqBRY\lib\site-packages\allauth\socialaccount\providers\google\views.py", 
line 22, in complete_login
    response["id_token"],
```

**Comment by suneethsunx** [comment]
I'm also having same issue
Did you found any way, if so please tell ...

**Comment by suneethsunx** [comment]
I'm having same issue with google auth

`  File "/home/suneeth/Documents/Workspace/JWT-allauth-demo/backend/venv/lib/python3.10/site-packages/allauth/socialaccount/providers/google/views.py", line 23, in complete_login
    response["id_token"],
TypeError: string indices must be integers`

@5no0p did you found any solution for this

**Comment by suneethsunx** [comment]
```
  File "/home/suneeth/Documents/Workspace/JWT-allauth-demo/backend/venv/lib/python3.10/site-packages/allauth/socialaccount/providers/google/views.py", line 23, in complete_login
    response["id_token"],
TypeError: string indices must be integers
```

**Comment by 5no0p** [comment]
Downgrade to 0.51.0 @suneethsunx

**Comment by pennersr** [comment]
Closing, this is an issue in `dj_rest_auth`

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3253
