### ISSUE TITLE
Patreon logins fail

### ISSUE THREAD

**Issue by nstephenh** [pennersr/django-allauth#3294]
I have Patreon integration set up, and it recently stated failing. Ths scope is as follows: 
        'SCOPE': ['identity', 'identity[email]', 'campaigns', 'campaigns.members'],

And the error I am getting is the following:

Traceback (most recent call last):
  File "/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/env/lib/python3.10/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/env/lib/python3.10/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 147, in dispatch
    login = self.adapter.complete_login(
  File "/env/lib/python3.10/site-packages/allauth/socialaccount/providers/patreon/views.py", line 40, in complete_login
    member_id = extra_data["relationships"]["memberships"]["data"][0]["id"]

Exception Type: TypeError at /accounts/patreon/login/callback/
Exception Value: 'NoneType' object is not subscriptable
Request information:
USER: AnonymousUser

We haven't changed anything recently so we are unsure why this error started appearing. We were wondering if something updated in allauth recently, or something on patreon's end.

**Comment by Fuzzwah** [comment]
I'm facing the same problem. I haven't updated allauth recently so I can only conclude that something on Patreon's end has changed.

**Comment by Fuzzwah** [comment]
I was in the middle of debugging (for a while I was finding that the callback response from Patreon was empty), when it suddenly started working again.

I think whatever Patreon busted on their side has been fixed.

**Comment by Fuzzwah** [comment]
Happening again now :(

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3294
