### ISSUE TITLE
Need help with google auth in django using mongodb cloud database

### ISSUE THREAD

**Issue by PrasannaKumaran** [pennersr/django-allauth#3362]
Hey guys. So I am working on a project which uses mongodb cloud databse. I implemented django-allauth with google as mentioned in tutorial videos but when I try to migrate I end up with the error given below. I am stuck on this for a while and would appreciate any help. I tried all the ways I could find on stackoverflow and other tutorials like managing the library versions but am still facing the same problem. 

Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, sessions, sites, socialaccount
Running migrations:
  Applying socialaccount.0004_alter_socialaccount_id_alter_socialapp_id_and_more...Not implemented alter command for SQL ALTER TABLE "socialaccount_socialaccount" ALTER COLUMN "id" TYPE long
Traceback (most recent call last):
  File "D:\mlOpsProj\mlops\lib\site-packages\djongo\cursor.py", line 51, in execute
    self.result = Query(
  File "D:\mlOpsProj\mlops\lib\site-packages\djongo\sql2mongo\query.py", line 784, in __init__
    self._query = self.parse()
  File "D:\mlOpsProj\mlops\lib\site-packages\djongo\sql2mongo\query.py", line 876, in parse
    raise e
  File "D:\mlOpsProj\mlops\lib\site-packages\djongo\sql2mongo\query.py", line 857, in parse
    return handler(self, statement)
  File "D:\mlOpsProj\mlops\lib\site-packages\djongo\sql2mongo\query.py", line 889, in _alter
    query = AlterQuery(self.db, self.connection_properties, sm, self._params)
  File "D:\mlOpsProj\mlops\lib\site-packages\djongo\sql2mongo\query.py", line 425, in __init__
    super().__init__(*args)
  File "D:\mlOpsProj\mlops\lib\site-packages\djongo\sql2mongo\query.py", line 84, in __init__
    super().__init__(*args)
  File "D:\mlOpsProj\mlops\lib\site-packages\djongo\sql2mongo\query.py", line 62, in __init__
    self.parse()
  File "D:\mlOpsProj\mlops\lib\site-packages\djongo\sql2mongo\query.py", line 441, in parse
    self._alter(statement)
  File "D:\mlOpsProj\mlops\lib\site-packages\djongo\sql2mongo\query.py", line 500, in _alter
    raise SQLDecodeError(f'Unknown token: {tok}')
djongo.exceptions.SQLDecodeError: 

        Keyword: Unknown token: TYPE
        Sub SQL: None
        FAILED SQL: ('ALTER TABLE "socialaccount_socialaccount" ALTER COLUMN "id" TYPE long',)
        Params: ([],)
        Version: 1.3.6

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\mlOpsProj\mlops\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\mlOpsProj\mlops\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\mlOpsProj\machinelearning_development\manage.py", line 22, in <module>
    main()
  File "D:\mlOpsProj\machinelearning_development\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "D:\mlOpsProj\mlops\lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "D:\mlOpsProj\mlops\lib\site-packages\django\core\management\__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\mlOpsProj\mlops\lib\site-packages\django\core\management\base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\mlOpsProj\mlops\lib\site-packages\django\core\management\base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "D:\mlOpsProj\mlops\lib\site-packages\django\core\management\base.py", line 98, in wrapped 
    res = handle_func(*args, **kwargs)
  File "D:\mlOpsProj\mlops\lib\site-packages\django\core\management\commands\migrate.py", line 290, in handle
    post_migrate_state = executor.migrate(
  File "D:\mlOpsProj\mlops\lib\site-packages\django\db\migrations\executor.py", line 131, in migrate
    state = self._migrate_all_forwards(
  File "D:\mlOpsProj\mlops\lib\site-packages\django\db\migrations\executor.py", line 163, in _migrate_all_forwards
    state = self.apply_migration(
  File "D:\mlOpsProj\mlops\lib\site-packages\django\db\migrations\executor.py", line 248, in apply_migration
    state = migration.apply(state, schema_editor)
  File "D:\mlOpsProj\mlops\lib\site-packages\django\db\migrations\migration.py", line 131, in apply
    operation.database_forwards(
  File "D:\mlOpsProj\mlops\lib\site-packages\django\db\migrations\operations\fields.py", line 235, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "D:\mlOpsProj\mlops\lib\site-packages\django\db\backends\base\schema.py", line 747, in alter_field
    self._alter_field(
  File "D:\mlOpsProj\mlops\lib\site-packages\django\db\backends\base\schema.py", line 963, in _alter_field
    self.execute(
  File "D:\mlOpsProj\mlops\lib\site-packages\django\db\backends\base\schema.py", line 192, in execute
    cursor.execute(sql, params)
  File "D:\mlOpsProj\mlops\lib\site-packages\django\db\backends\utils.py", line 103, in execute   
    return super().execute(sql, params)
  File "D:\mlOpsProj\mlops\lib\site-packages\django\db\backends\utils.py", line 67, in execute    
    return self._execute_with_wrappers(
  File "D:\mlOpsProj\mlops\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\mlOpsProj\mlops\lib\site-packages\django\db\backends\utils.py", line 89, in _execute   
    return self.cursor.execute(sql, params)
  File "D:\mlOpsProj\mlops\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\mlOpsProj\mlops\lib\site-packages\django\db\backends\utils.py", line 89, in _execute   
    return self.cursor.execute(sql, params)
  File "D:\mlOpsProj\mlops\lib\site-packages\djongo\cursor.py", line 59, in execute
    raise db_exe from e
django.db.utils.DatabaseError

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3362
