### ISSUE TITLE
steam openid fails

### ISSUE THREAD

**Issue by negstek** [pennersr/django-allauth#3404]
Hi here, I just tried to implement steam openid login with allauth but it fails with this error:

```
Missing required parameter in response from https://steamcommunity.com/openid/login: ('http://specs.openid.net/auth/2.0', 'assoc_type')
Traceback (most recent call last):
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/openid/message.py", line 481, in getArg
    return self.args[args_key]
           ~~~~~~~~~^^^^^^^^^^
KeyError: ('http://specs.openid.net/auth/2.0', 'assoc_type')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/openid/consumer/consumer.py", line 1286, in _requestAssociation
    assoc = self._extractAssociation(response, assoc_session)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/openid/consumer/consumer.py", line 1402, in _extractAssociation
    assoc_type = assoc_response.getArg(OPENID_NS, 'assoc_type', no_default)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/openid/message.py", line 484, in getArg
    raise KeyError((namespace, key))
KeyError: ('http://specs.openid.net/auth/2.0', 'assoc_type')
[30/Aug/2023 21:15:06] "GET /accounts/steam/login/ HTTP/1.1" 302 0
Internal Server Error: /accounts/steam/callback/
Traceback (most recent call last):
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/allauth/socialaccount/providers/openid/views.py", line 133, in get
    login = provider.sociallogin_from_response(request, response)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/allauth/socialaccount/providers/steam/provider.py", line 66, in sociallogin_from_response
    steam_api_key = self.app.secret
                    ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'secret'
[30/Aug/2023 21:15:10] "GET /accounts/steam/callback/?janrain_nonce=2023-08-30T21%3A15%3A06Zwe4VmX&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198426829752&openid.identity=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198426829752&openid.return_to=http%3A%2F%2F127.0.0.1%3A8000%2Faccounts%2Fsteam%2Fcallback%2F%3Fjanrain_nonce%3D2023-08-30T21%253A15%253A06Zwe4VmX&openid.response_nonce=2023-08-30T21%3A15%3A08Zr%2B8TWBmePJrgT76WD%2BRkVAk57xI%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=8Evslkd6wcY5pjYHgNBTiSidKtE%3D HTTP/1.1" 500 93736
```

I don't know if I did something wrong in my implementation of allauth or if this is a real issue.

**Comment by pennersr** [comment]
Confirmed, this indeed does not work.

**Comment by pennersr** [comment]
Fixed via fccd33f6

**Comment by negstek** [comment]
@pennersr   thank you for your fast fix, I put it into the lib and it works fine, big up to you and your awesome project!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3404
