### ISSUE TITLE
steam login broken?

### ISSUE THREAD

**Issue by goern** [pennersr/django-allauth#3414]
Heya, I an having problem with the steam module, the config I made seems ok, and my error is different from #3404 but I get a 

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/accounts/steam/callback/?janrain_nonce=2023-09-05T13%3A26%3A09Z1YUEo3&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198029983752&openid.identity=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198029983752&openid.return_to=http%3A%2F%2Flocalhost%3A8000%2Faccounts%2Fsteam%2Fcallback%2F%3Fjanrain_nonce%3D2023-09-05T13%253A26%253A09Z1YUEo3&openid.response_nonce=2023-09-05T13%3A26%3A11Z4KkMWbUVD9vB%2F2ABsH%2FQBYnsZAI%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=AaVUzLjEEgVBGkxb3DxRZZg%2FGVw%3D

Django Version: 4.2.5
Python Version: 3.10.12
Installed Applications:
['allauth',
 'allauth.account',
 'allauth.socialaccount.providers.openid',
 'allauth.socialaccount.providers.discord',
 'allauth.socialaccount.providers.github',
 'allauth.socialaccount.providers.google',
 'allauth.socialaccount.providers.microsoft',
 'allauth.socialaccount.providers.reddit',
 'allauth.socialaccount.providers.steam',
 'allauth.socialaccount.providers.twitch',
 'allauth.socialaccount',
 'bootstrap4',
 'fontawesomefree',
 'crispy_bootstrap4',
 'crispy_forms',
 'django_extensions',
 'django_plotly_dash.apps.DjangoPlotlyDashConfig',
 'django.contrib.admin',
 'django_admin_listfilter_dropdown',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'dpd_static_support',
 'explorer',
 'django_prometheus',
 'telemetry.apps.TelemetryConfig']
Installed Middleware:
['django_prometheus.middleware.PrometheusBeforeMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django_plotly_dash.middleware.BaseMiddleware',
 'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']



Traceback (most recent call last):
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/allauth/socialaccount/providers/openid/views.py", line 133, in get
    login = provider.sociallogin_from_response(request, response)
  File "/var/home/goern/Source/github.com/b4mad/racing/components/paddock/venv/lib64/python3.10/site-packages/allauth/socialaccount/providers/steam/provider.py", line 66, in sociallogin_from_response
    steam_api_key = self.app.secret

Exception Type: AttributeError at /accounts/steam/callback/
Exception Value: 'NoneType' object has no attribute 'secret'
```

/kind bug

**Comment by pennersr** [comment]
Duplicate of #3404

**Comment by goern** [comment]
oci, the fix is unreleased. sorry for not seeing that earlier. 

@pennersr when are you doing to roll a new release?

**Comment by pennersr** [comment]
That is not clear yet, you can always use...

 `pip install git+https://github.com/pennersr/django-allauth.git@main#egg=django-allauth` 

...if you want a release today.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3414
