### ISSUE TITLE
Lost middleware in the recent versions of django-allauth

### ISSUE THREAD

**Issue by Sciencealone** [pennersr/django-allauth#3426]
## Summary

Hello and thank you for the great tool!

Unfortunately, the recent versions of django-allauth (0.56.0+) contain some instability, preventing the launch of my app very often. I am using it together with Phusion Passenger and it hardly can run an updated version.

## Details
````
Traceback (most recent call last):
  File "/usr/share/passenger/helper-scripts/wsgi-loader.py", line 369, in <module>
    app_module = load_app()

  File "/usr/share/passenger/helper-scripts/wsgi-loader.py", line 76, in load_app
    return imp.load_source('passenger_wsgi', startup_file)

  File "/usr/lib/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "PROJECT_PATH/passenger_wsgi.py", line 1, in <module>
    
import APP_NAME.wsgi
  File "PROJECT_PATH/APP_NAME/wsgi.py", line 16, in <module>
    
application = get_wsgi_application()
  File "LOCAL_PYTHON_PATH/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    
django.setup(set_prefix=False)

  File "LOCAL_PYTHON_PATH/site-packages/django/__init__.py", line 24, in setup
    
apps.populate(settings.INSTALLED_APPS)
  File "LOCAL_PYTHON_PATH/site-packages/django/apps/registry.py", line 124, in populate
    
app_config.ready()
  File "LOCAL_PYTHON_PATH/site-packages/allauth/account/apps.py", line 15, in ready
    
raise ImproperlyConfigured(
django.core.exceptions.
ImproperlyConfigured
: 
allauth.account.middleware.AccountMiddleware must be added to settings.MIDDLEWARE

Could not spawn process for application APP_PATH: The application process exited prematurely.
````

Definitely, django-allauth has been configured according to the guide https://django-allauth.readthedocs.io/en/latest/installation/quickstart.html, so this potentially missing middleware link does exist. I tried to move it back and forth in the list of middlewares without any result. How can I fix this issue?

## Configuration

- Ubuntu 22.04.3 LTS
- Phusion Passenger 6.0.18
- Python 3.10.12
- Django 4.2.5
- Django-allauth 0.56.0+

**Comment by pennersr** [comment]
That error is raised here:

https://github.com/pennersr/django-allauth/blob/0.56.1/allauth/account/apps.py#L14

You mention that the middleware has been installed properly, but the referenced code above is really as basic as it gets. Please double check your `settings.MIDDLEWARE` -- this really is a local deployment issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3426
