### ISSUE TITLE
Exception using OpenIDProvider since 0.55

### ISSUE THREAD

**Issue by riconnon** [pennersr/django-allauth#3444]
I think this this refactor https://github.com/pennersr/django-allauth/commit/cc5279bb61dba9cf0fafb10f4ae175c018749f1f has caused an issue with OpenIDProvider (and possibly others)

Since `Provider.sociallogin_from_response` assumes that `self.app` is not `None` and `OpenIDProvider` has `use_apps` set to false which means that `self.app` may be (or always is?) `None`

I believe that in the case that `self.app` is none `self.id` should be used rather than `self.app.provider_id`

**Comment by pennersr** [comment]
Can you please add the exception/stack trace you are seeing?

**Comment by riconnon** [comment]
Ah, sorry, should have included that straight away...
```
Internal Server Error: /accounts/openid/callback/
Traceback (most recent call last):
  File "/opt/hunter2/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hunter2/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/hunter2/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hunter2/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hunter2/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hunter2/venv/lib/python3.11/site-packages/allauth/socialaccount/providers/openid/views.py", line 133, in get 
    login = provider.sociallogin_from_response(request, response)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hunter2/venv/lib/python3.11/site-packages/allauth/socialaccount/providers/base/provider.py", line 77, in sociallogin_from_response
    provider=self.app.provider_id or self.app.provider,
             ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'provider_id'                                                                                                                       
```

**Comment by pennersr** [comment]
Can I see your settings as well? I notice that you have `/accounts/openid/callback/`, where `openid` is normally expected to be the `id` of the *specific* OIDC provider. For example, if you use:

``` python

SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        "APPS": [
            {
                "provider_id": "keycloak",
                "name": "OIDC KC",
                "client_id": "...",
                "secret": "...",
                "settings": {
                    "server_url": "http://keycloak:8080/realms/master/.well-known/openid-configuration",
                },
            },
```

Then, that URL will be `/accounts/keycloak/callback/`.

**Comment by pennersr** [comment]
I am sorry, I completely misinterpreted your ticket as relating to OpenID Connect, but you are referring to OpenID. I'll take a renewed look.

**Comment by riconnon** [comment]
@pennersr no problem...
I have the following settings:
```
{
  "openid": {
    "SERVERS": [
      {
        "id": "steam",
        "name": "Steam",
        "openid_url": "https://steamcommunity.com/openid",
        "stateless": true
      }
    ]
  }
}
```
I'm aware of the new `SteamOpenIDProvider` but haven't migrated to it yet, since it results in collecting/storing more account data I need to make sure this is inline with privacy policies, etc. This configuration has worked well for a good few years so far though!

**Comment by pennersr** [comment]
Fixed: 24049ad7

**Comment by riconnon** [comment]
Thanks @pennersr 
Do you have an idea when this might be included in a release?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3444
