### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'email_address' error on email confirm.

### ISSUE THREAD

**Issue by kushalmraut** [pennersr/django-allauth#3508]
version: `django-allauth==0.55.0`

```
Internal Server Error: /accounts/confirm-email/MjI4:1qyVJR:7M0Ua__gMudIrFDwqkxPK8BWn7GFRGSwc-kStKXgWjc/
Traceback (most recent call last):
  File "/Users/kushal/Documents/projects/anahit/anahit_venv_3-11/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kushal/Documents/projects/anahit/anahit_venv_3-11/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kushal/Documents/projects/anahit/anahit_venv_3-11/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kushal/Documents/projects/anahit/anahit_venv_3-11/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kushal/Documents/projects/anahit/anahit_venv_3-11/lib/python3.11/site-packages/allauth/account/views.py", line 301, in get
    ctx = self.get_context_data()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kushal/Documents/projects/anahit/anahit_venv_3-11/lib/python3.11/site-packages/allauth/account/views.py", line 414, in get_context_data
    "can_confirm": self.object.email_address.can_set_verified(),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'email_address'
[log.py:241 -        log_response()] Internal Server Error: /accounts/confirm-email/MjI4:1qyVJR:7M0Ua__gMudIrFDwqkxPK8BWn7GFRGSwc-kStKXgWjc/
Traceback (most recent call last):
  File "/Users/kushal/Documents/projects/anahit/anahit_venv_3-11/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kushal/Documents/projects/anahit/anahit_venv_3-11/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kushal/Documents/projects/anahit/anahit_venv_3-11/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kushal/Documents/projects/anahit/anahit_venv_3-11/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kushal/Documents/projects/anahit/anahit_venv_3-11/lib/python3.11/site-packages/allauth/account/views.py", line 301, in get
    ctx = self.get_context_data()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kushal/Documents/projects/anahit/anahit_venv_3-11/lib/python3.11/site-packages/allauth/account/views.py", line 414, in get_context_data
    "can_confirm": self.object.email_address.can_set_verified(),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'email_address'
```

I am getting this error when `/accounts/confirm-email/MjI4:1qyVJR:7M0Ua__gMudIrFDwqkxPK8BWn7GFRGSwc-kStKXgWjc/`
url is triggered for multiple time.

**Comment by pennersr** [comment]
What version are you running? This looks identical to: https://github.com/pennersr/django-allauth/issues/3402

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3508
