### ISSUE TITLE
assoc_type missing error with steam auth

### ISSUE THREAD

**Issue by negstek** [pennersr/django-allauth#3516]
Hi, I have this error in my console when I'm using allauth with steam

```
Missing required parameter in response from https://steamcommunity.com/openid/login: ('http://specs.openid.net/auth/2.0', 'assoc_type')
Traceback (most recent call last):
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/openid/message.py", line 481, in getArg
    return self.args[args_key]
           ~~~~~~~~~^^^^^^^^^^
KeyError: ('http://specs.openid.net/auth/2.0', 'assoc_type')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/openid/consumer/consumer.py", line 1286, in _requestAssociation
    assoc = self._extractAssociation(response, assoc_session)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/openid/consumer/consumer.py", line 1402, in _extractAssociation
    assoc_type = assoc_response.getArg(OPENID_NS, 'assoc_type', no_default)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/openid/message.py", line 484, in getArg
    raise KeyError((namespace, key))
KeyError: ('http://specs.openid.net/auth/2.0', 'assoc_type')
```

and the login method failed

**Comment by negstek** [comment]
any idea to solve it ?

**Comment by negstek** [comment]
![image](https://github.com/pennersr/django-allauth/assets/883536/60452b5d-403a-48d4-bf8b-3f0a35ddfa25)
Steam change its login method recently, maybe this is a side effect of this
source of the error is that "associations not supported"

**Comment by pennersr** [comment]
I've just tested Steam and it "works-for-me".

Just to be sure, my `settings.py` contains:

```
SOCIALACCOUNT_PROVIDERS = {
    "steam": {
        "APP": {
            "client_id": "123456789",
            "secret": "123456789",
        }
    },
}

INSTALLED_APPS = 
...
    "allauth.socialaccount.providers.steam"
```

**Comment by negstek** [comment]
Hi @pennersr. Thank you very much, you save my week, I sucked when I updated the package by forgetting to read the release notes. I haven't seen the breaking changes in the settings configuration (personal note: RTFM!!!). All works fine on my site now except that this errors is back in my vscode terminal during debug despite database reset:
```
Missing required parameter in response from https://steamcommunity.com/openid/login: ('http://specs.openid.net/auth/2.0', 'assoc_type')
Traceback (most recent call last):
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/openid/message.py", line 481, in getArg
    return self.args[args_key]
           ~~~~~~~~~^^^^^^^^^^
KeyError: ('http://specs.openid.net/auth/2.0', 'assoc_type')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/openid/consumer/consumer.py", line 1286, in _requestAssociation
    assoc = self._extractAssociation(response, assoc_session)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/openid/consumer/consumer.py", line 1402, in _extractAssociation
    assoc_type = assoc_response.getArg(OPENID_NS, 'assoc_type', no_default)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/negstek/.cache/pypoetry/virtualenvs/django-all-auth-to-steam-83qxtO4Z-py3.11/lib/python3.11/site-packages/openid/message.py", line 484, in getArg
    raise KeyError((namespace, key))
KeyError: ('http://specs.openid.net/auth/2.0', 'assoc_type')
```
(the error does not prevent the connection, it still works fine)
Do you think it comes from the openid library, allauth or from my side ?

**Comment by pennersr** [comment]
Sorry, the above does not ring a bell...

**Comment by maxcorbeau** [comment]
**Actually I wasn't paying attention to the logs:**
 - The error `KeyError: ('http://specs.openid.net/auth/2.0', 'assoc_type')` is logged
 - However the underlying except is caught so Django survives it and Steam login works for me

**Solution**: `assoc_type` is missing because Steam works in stateless mode, so I followed instructions given in https://docs.allauth.org/en/latest/socialaccount/providers/openid.html:

```
SOCIALACCOUNT_PROVIDERS = {
...
    "openid": {
        "SERVERS": [
            {
                "id": "steam",
                "name": "Steam",
                "openid_url": "https://steamcommunity.com/openid",
                "stateless": True,
            },
        ],
    },
...
}
```

Now the logger no longer logs an error.

Please note this is not specific to Django Allauth, but the way Openid was implemented by Steam, as you find other libraries reporting the same problem: https://github.com/jaredhanson/passport-openid/issues/1

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3516
