### ISSUE TITLE
 _app_settings = AppSettings("ACCOUNT_")

### ISSUE THREAD

**Issue by kamalktwl** [pennersr/django-allauth#3628]
When i  install allauth

`pip install django-allauth`

but return error 

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kamal/SB_project/Pythons/venvlist/strip/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/kamal/SB_project/Pythons/venvlist/strip/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/home/kamal/SB_project/Pythons/venvlist/strip/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/kamal/SB_project/Pythons/venvlist/strip/lib/python3.10/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "myenv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "myenv/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "myenv/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "myenv/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "myenv/lib/python3.10/site-packages/allauth/account/models.py", line 13, in <module>
    from . import app_settings, signals
  File "myenv/lib/python3.10/site-packages/allauth/account/app_settings.py", line 402, in <module>
    _app_settings = AppSettings("ACCOUNT_")
  File "myenv/lib/python3.10/site-packages/allauth/account/app_settings.py", line 23, in __init__
    assert (
AssertionError

**Comment by pennersr** [comment]
You did not paste all -- what is the AssertionError that you are getting?

**Comment by kamalktwl** [comment]
when i install in pip and also added setting same that time comes out error 

i have install in pip command 
`pip install django-allauth`

settings.py
INSTALLED_APPS = [
    'subscription',
    # ...
    'allauth',
    'allauth.account',
]
![errors_](https://github.com/pennersr/django-allauth/assets/9162846/182acf61-3cfe-4c48-91b1-641e4964ceda)

**Comment by pennersr** [comment]
This points to an error in your configuration. Have a look here at the various checks that are being done:

https://github.com/pennersr/django-allauth/blob/main/allauth/account/app_settings.py#L27

Then, check those against your configuration. Or, put a `breakpoint()` in there.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3628
