### ISSUE TITLE
ModuleNotFoundError: No module named 'user'

### ISSUE THREAD

**Issue by fergbrain** [pennersr/django-allauth#3686]
When upgrading from 0.60.1 to 0.61.1, I'm now getting a "ModuleNotFoundError: No module named 'user'" when a user tries to confirm their email (i.e. clicks on the email link).

```
ERROR 2024-03-16 17:25:15,653 log 3516 6222032896 Internal Server Error: /account/confirm-email/MTQ0:1rlXmQ:9V0b_s5NhMiWNteIQTBHD8Wle1oLh7Z3g3XZ_E9pa9o/
Traceback (most recent call last):
  File "{REDACTED}/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "{REDACTED}/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "{REDACTED}/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "{REDACTED}/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "{REDACTED}/venv/lib/python3.8/site-packages/allauth/account/views.py", line 343, in get
    return _ajax_response(self.request, resp, data=self.get_ajax_data())
  File "{REDACTED}/venv/lib/python3.8/site-packages/allauth/account/views.py", line 459, in get_ajax_data
    ret["user"] = {"display": user_display(self.object.email_address.user)}
  File "{REDACTED}/venv/lib/python3.8/site-packages/allauth/account/utils.py", line 85, in user_display
    _user_display_callable = import_callable(f)
  File "{REDACTED}/venv/lib/python3.8/site-packages/allauth/utils.py", line 145, in import_callable
    ret = import_attribute(path_or_callable)
  File "{REDACTED}/venv/lib/python3.8/site-packages/allauth/utils.py", line 139, in import_attribute
    ret = getattr(importlib.import_module(pkg), attr)
  File "/opt/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
```

I'm using Django 3.2.23 and Python 3.8.

**Comment by fergbrain** [comment]
I think the issue is related the change made in 35fc1ed9a496b1f0d385f53bb9ab31b5e21cf614. @mecampbellsoup had a [similar issues, but they were implementing it incorrectly (it sounds like)](https://github.com/pennersr/django-allauth/commit/35fc1ed9a496b1f0d385f53bb9ab31b5e21cf614#r138857516)

I don't believe I'm doing anything weird (I used the django cookiecutter template).

**Comment by pennersr** [comment]
Possibly, you're running into import cyclces. Check if you have `ACCOUNT_USER_DISPLAY` defined, and where it is pointing to. Otherwise, put a breakpoint at `allauth/account/utils.py", line 85, in user_display`. 

Other than that, this is not actionable on this end.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3686
