### ISSUE TITLE
Tests fail if `ACCOUNT_USER_MODEL_USERNAME_FIELD = None`

### ISSUE THREAD

**Issue by nanorepublica** [pennersr/django-allauth#3714]
I found this issue (#1852) which touches upon the same problem I am currently facing. I am creating a custom provider for Xero and our custom user model doesn't have a username field. 

```py
======================================================================
ERROR: moneymover.apps.accounting_integrations.allauth.providers.xero.tests.XeroTests.test_account_refresh_token_saved_next_login
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/allauth/socialaccount/tests/__init__.py", line 313, in test_account_refresh_token_saved_next_login
    self.test_account_tokens(multiple_login=True)
  File "/usr/local/lib/python3.10/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/allauth/socialaccount/tests/__init__.py", line 273, in test_account_tokens
    self.client.login(username=user.username, password="test")
AttributeError: 'User' object has no attribute 'username'

----------------------------------------------------------------------
```

My suggestion would be to switch `user.username` for `user.get_username()` in the login method. So it would be
```py
    self.client.login(username=user.get_username(), password="test") 
```

**Comment by pennersr** [comment]
It seems that you are running/reusing the allauth unittests within your own project. The allauth unit tests are not intended for that purpose.

**Comment by nanorepublica** [comment]
Thanks for confirming this. 

A quick follow up question, are there any contributing docs so I can set up a fork locally?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3714
