### ISSUE TITLE
IntegrityError on email change if user email field is unique

### ISSUE THREAD

**Issue by Okan0** [pennersr/django-allauth#3741]
### Background
We are using a central account management system in Django that allows users to log in using their email address, with each email address expected to be unique to prevent data leaks. We have specific Django settings configured to meet these requirements.
<details>
  <summary>ALLAUTH Settings</summary>

```
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_CHANGE_EMAIL = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_EMAIL_NOTIFICATIONS = True
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True
ACCOUNT_PRESERVE_USERNAME_CASING = False
ACCOUNT_PREVENT_ENUMERATION = "strict" 
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = True
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_REAUTHENTICATION_TIMEOUT = 300
ACCOUNT_REAUTHENTICATION_REQUIRED = False
```
</details>

<details>
  <summary>User Model</summary>

```
class User(AbstractUser):
    username_validator = UnicodeUsernameValidator()

    # make the email field required
    email = models.EmailField(_("email address"), blank=False, null=False, unique=True)

    # [...] additional properties

    def save(self, update_fields=None, *args, **kwargs):
        _email = self.email
        if update_fields is None or "email" in update_fields:
            _email = IDNADecoder.idna_encode_email(self.email.lower())
        if self.email != _email:
            self.email = _email
        return super().save(*args, **kwargs)

    # set email as username
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()
```
</details>

### Description of the Issue
Currently, there is an issue when a user attempts to change their email address. When a user changes their email address and follows the confirmation link, it results in an internal server error (500), if an user with the same email address and uncomplete registration exists. In addition, a new entry for "EmailAddress" is created in the background, whereby bla@dev.de is now assigned to the user demo@demo.de and the old entry for the user bla@dev.de remains in place.

Even if the problem is probably caused by the user model, my assumption would have been that this is intercepted.

### Steps to Reproduce

1. Register a user with the email address "bla@dev.de".
2. Register another user with a different email address, e.g., "demo@demo.de".
3. finish the registration of "demo@demo.de"
4. Change the email address of the user "demo@demo.de" to "bla@dev.de".
5. Confirm the email change using the link sent via email
![image](https://github.com/pennersr/django-allauth/assets/12232622/24b68d5f-97df-405e-add4-d791f423b85e)
![image](https://github.com/pennersr/django-allauth/assets/12232622/1f749108-3614-4425-a460-84e566495b22)

<details>
  <summary>Stacktrace</summary>
```
Environment:


Request Method: POST
Request URL: http://accounts-dev.localhost:19080/accounts/confirm-email/MTU:1ryotT:OL4yi9ZahCtvCNZUrPEKuYqnGvYYZW6XT12Rke5LqzI/

Django Version: 4.2.11
Python Version: 3.9.17
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'oauth2_provider',
 'rest_framework',
 'allauth',
 'allauth.account',
 'allauth.mfa',
 'allauth.usersessions',
 'compressor',
 'core.apps.CoreConfig',
 'core.apps.CoreAdminConfig',
 'oauth2.apps.Oauth2Config']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'allauth.account.middleware.AccountMiddleware',
 'allauth.usersessions.middleware.UserSessionsMiddleware']



Traceback (most recent call last):
  File "/workspace/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/workspace/venv/lib/python3.9/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)

The above exception (duplicate key value violates unique constraint "auth_user_email_key"
DETAIL:  Key (email)=(bla@dev.de) already exists.) was the direct cause of the following exception:
  File "/workspace/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/workspace/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/venv/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/workspace/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/workspace/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/workspace/venv/lib/python3.9/site-packages/allauth/account/views.py", line 360, in post
    email_address = confirmation.confirm(self.request)
  File "/workspace/venv/lib/python3.9/site-packages/allauth/account/models.py", line 116, in confirm
    confirmed = get_adapter().confirm_email(request, email_address)
  File "/workspace/venv/lib/python3.9/site-packages/allauth/account/adapter.py", line 541, in confirm_email
    email_address.set_as_primary(conditional=(not app_settings.CHANGE_EMAIL))
  File "/workspace/venv/lib/python3.9/site-packages/allauth/account/models.py", line 85, in set_as_primary
    user_email(self.user, self.email, commit=True)
  File "/workspace/venv/lib/python3.9/site-packages/allauth/account/utils.py", line 123, in user_email
    return user_field(user, app_settings.USER_MODEL_EMAIL_FIELD, *args, commit=commit)
  File "/workspace/venv/lib/python3.9/site-packages/allauth/account/utils.py", line 110, in user_field
    user.save(update_fields=[field])
  File "/workspace/src/core/models/user.py", line 60, in save
    return super().save(*args, **kwargs)
  File "/workspace/venv/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 76, in save
    super().save(*args, **kwargs)
  File "/workspace/venv/lib/python3.9/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/workspace/venv/lib/python3.9/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/workspace/venv/lib/python3.9/site-packages/django/db/models/base.py", line 990, in _save_table
    updated = self._do_update(
  File "/workspace/venv/lib/python3.9/site-packages/django/db/models/base.py", line 1054, in _do_update
    return filtered._update(values) > 0
  File "/workspace/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1231, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/workspace/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/workspace/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/workspace/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/workspace/venv/lib/python3.9/site-packages/sentry_sdk/integrations/django/__init__.py", line 641, in execute
    result = real_execute(self, sql, params)
  File "/workspace/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/workspace/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/workspace/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/workspace/venv/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/workspace/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/workspace/venv/lib/python3.9/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)

Exception Type: IntegrityError at /accounts/confirm-email/MTU:1ryotT:OL4yi9ZahCtvCNZUrPEKuYqnGvYYZW6XT12Rke5LqzI/
Exception Value: duplicate key value violates unique constraint "auth_user_email_key"
DETAIL:  Key (email)=(bla@dev.de) already exists.

```
</details>

**Comment by pennersr** [comment]
Django has the email field defined like this:

```
class AbstractUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email address"), blank=True)
```

You deviate from that by doing:

```
    email = models.EmailField(_("email address"), blank=False, null=False, unique=True)
```

So, you're making it unique. When the user model has an email field allauth populates that, even if the email address is still unverified. Note that allauth allows for 2 different users to have the same email address, though only one user can have it listed as verified.

Given your user model definition, I think the only way around would be to not populate the email field for users unless it is truly verified. You could do that by setting `ACCOUNT_USER_MODEL_EMAIL_FIELD` to `None` -- then allauth won't do any attempt to populate the field. Then, you could use e.g. the `email_confirmed` signal to actually start populating the field. 

Though, you can also ask yourself, why go against the flow, and why not just use Django's standard way of working? Or, perhaps remove the email field from the user altogether as it really is just denormalized data (of the `EmailAddress` model).

**Comment by Okan0** [comment]
Hi, thanks for the quick reply. I guess that will help :)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3741
