### ISSUE TITLE
Telegram views CallbackView 'bool' object has no attribute 'pop'

### ISSUE THREAD

**Issue by I-SMAF** [pennersr/django-allauth#3764]
![error](https://github.com/pennersr/django-allauth/assets/77810316/15285931-c986-4e66-87f4-34b5f09fbee6)

> "GET /accounts/telegram/login/callback/?state=WINdxvbAJ9zvOFaL HTTP/1.1"

```
Internal Server Error: /accounts/telegram/login/callback/
Traceback (most recent call last):
  File "Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Lib\site-packages\allauth\socialaccount\providers\telegram\views.py", line 47, in post
    hash = data.pop("hash")
           ^^^^^^^^
AttributeError: 'bool' object has no attribute 'pop'
```

```
@method_decorator(csrf_exempt, name="dispatch")
class CallbackView(View):
    def get(self, request):
        return render(request, "telegram/callback.html")

    def post(self, request):
        adapter = get_adapter()
        provider = adapter.get_provider(request, TelegramProvider.id)

        state_id = request.GET.get("state")
        if not state_id:
            return render_authentication_error(
                request,
                provider=provider,
            )

        result = request.POST.get("tgAuthResult")
        padding = "=" * (4 - (len(result) % 4))
        data = json.loads(base64.b64decode(result + padding))
        hash = data.pop("hash")
        payload = "\n".join(sorted(["{}={}".format(k, v) for k, v in data.items()]))
        token = provider.app.secret
        token_sha256 = hashlib.sha256(token.encode()).digest()
        expected_hash = hmac.new(
            token_sha256, payload.encode(), hashlib.sha256
        ).hexdigest()
        auth_date = int(data.pop("auth_date"))
        auth_date_validity = provider.get_auth_date_validity()
        if hash != expected_hash or time.time() - auth_date > auth_date_validity:
            return render_authentication_error(
                request,
                provider=provider,
                extra_context={"response": data, "state_id": state_id},
            )
        login = provider.sociallogin_from_response(request, data)
        login.state = provider.unstash_redirect_state(request, state_id)
        return complete_social_login(request, login)
```

```
result = request.POST.get("tgAuthResult")
padding = "=" * (4 - (len(result) % 4))
data = json.loads(base64.b64decode(result + padding))
``` 
-----> data: False

**Comment by pennersr** [comment]
Something is wrong/unexpected in your `tgAuthResult`:

```
data = json.loads(base64.b64decode(result + padding))
```

In your case, that results in a boolean, which clearly has no `pop()`... but under normal circumstances that should not occur. I suspect something is wrong with your setup/config.

**Comment by pennersr** [comment]
See aa1a78d7 -- this fixes crashing on invalid `tgAuthResult`. It does not solve your issue though, but that is beyond control.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3764
