### ISSUE TITLE
How to replace socialaccount/base.html usage

### ISSUE THREAD

**Issue by lucas03** [pennersr/django-allauth#3778]
Hey,
I upgraded django-allauth recently from 0.57 to 0.62.1 and was suprised by this error. Firstly thanks for doing a great job of maintaining and improving django-allauth. I've been using it for quite a few years without many changes.

I have subpages for connected accounts + delete account, which I probably copied from documentation a decade ago. This is my socialaccount/connections.html page:
```
{% extends "socialaccount/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Connected Accounts" %}{% endblock %}
{% block account_nav_socialaccount_connections  %}active{% endblock %}

{% block account_content %}

{% if form.accounts %}
<p>{% blocktrans %}You can sign in to your account using any of the following third party accounts:{% endblocktrans %}</p>


<form method="post">
{% csrf_token %}

{% if form.non_field_errors %}
    <div class="alert alert-error">
        <a class="close" data-dismiss="alert">&times;</a>
        {% for non_field_error in form.non_field_errors %}
             {{ non_field_error }}
        {% endfor %}
    </div>
{% endif %}


<table class="table">
  <thead>
    <tr>
      <th>
	{% trans 'Provider' %}
      </th>
      <th>
	{% trans 'Account' %}
      </th>
    </tr>
  </thead>
  <tbody>
{% for base_account in form.accounts %}
{% with base_account.get_provider_account as account %}
    <tr>
      <td>
<label class="radio" for="id_account_{{base_account.id}}">
<input id="id_account_{{base_account.id}}" type="radio" name="account" value="{{base_account.id}}"/>
<span class="socialaccount_provider {{base_account.provider}} {{account.get_brand.id}}">{{account.get_brand.name}}</span>
</label>
      </td>
      <td>
	{{account}}
      </td>
    </tr>
{% endwith %}
{% endfor %}
  </tbody>
</table>

<div class="form-actions">
<button class="btn btn-danger" type="submit">{% trans 'Remove' %}</button>
</div>

</fieldset>

</form>

{% else %}
<div class="alert">
<strong>{% trans 'None!' %}</strong> {% trans 'You currently have no social network accounts connected to this account.' %}
</div>
{% endif %}

<h2>{% trans 'Add a 3rd Party Account' %}</h2>

<ul class="socialaccount_providers">
{% include "socialaccount/snippets/provider_list.html" with process="connect" %}
</ul>

{% include "socialaccount/snippets/login_extra.html" %}

{% endblock %}
```
after upgrade, I am hit with an error:

```
TemplateDoesNotExist at /accounts/3rdparty/
socialaccount/base.html
```

I found [this issue](https://github.com/pennersr/django-allauth/issues/3513), and tried both `socialaccount/base_entrance.html`
and `socialaccount/base_manage.html`, but that doesn't use my html (I override `account/base.html`). 

I can update socialaccount/connections.html with `{% extends "account/base.html" %}`, which renders forms with my html, but when I try to send the form, I get:
```
Traceback (most recent call last):
  File "/Users/lukasvojt/Projects/digrin/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lukasvojt/Projects/digrin/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lukasvojt/Projects/digrin/env/lib/python3.11/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lukasvojt/Projects/digrin/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lukasvojt/Projects/digrin/env/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lukasvojt/Projects/digrin/env/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lukasvojt/Projects/digrin/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lukasvojt/Projects/digrin/env/lib/python3.11/site-packages/allauth/account/mixins.py", line 68, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "/Users/lukasvojt/Projects/digrin/env/lib/python3.11/site-packages/django/forms/forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "/Users/lukasvojt/Projects/digrin/env/lib/python3.11/site-packages/django/forms/forms.py", line 192, in errors
    self.full_clean()
  File "/Users/lukasvojt/Projects/digrin/env/lib/python3.11/site-packages/django/forms/forms.py", line 328, in full_clean
    self._clean_form()
  File "/Users/lukasvojt/Projects/digrin/env/lib/python3.11/site-packages/django/forms/forms.py", line 349, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "/Users/lukasvojt/Projects/digrin/env/lib/python3.11/site-packages/allauth/socialaccount/forms.py", line 57, in clean
    flows.connect.validate_disconnect(self.request, account)
  File "/Users/lukasvojt/Projects/digrin/env/lib/python3.11/site-packages/allauth/socialaccount/internal/flows/connect.py", line 40, in validate_disconnect
    adapter.validate_disconnect(account, accounts)
    ^^^^^^^
```

I was searching through docs, changelog and googled a bit, but didn't find a solution. Is there a documentation or suggested approach I missed?

**Comment by pennersr** [comment]
This is due to:

https://github.com/pennersr/django-allauth/blob/0.58.0/ChangeLog.rst#backwards-incompatible-changes

Since that release, there is no more `socialaccount/base.html`. Instead, there is a distinction between 2 base templates, the entrance template (all that happens before authenticated), and the account management template. Try:

```
{% extends "socialaccount/base_manage.html" %}
```

**Comment by lucas03** [comment]
I did, but that does not work out for me:

> I found https://github.com/pennersr/django-allauth/issues/3513, and tried both socialaccount/base_entrance.html
and socialaccount/base_manage.html, but that doesn't use my html (I override account/base.html).

Did I forget to create another template file that would extend my account/base.html?

**Comment by pennersr** [comment]
There no longer is a `account/base.html` either.  I recommend you to have a look at the allauth templates. The connections page uses:

```
{% extends "socialaccount/base_manage.html" %}
```

That `base_manage` uses:

```
{% extends "allauth/layouts/manage.html" %}
```

The account `login.html` uses:

```
{% extends "account/base_entrance.html" %}
```

That base uses:

```
{% extends "allauth/layouts/entrance.html" %}
```

Meaning, if you want to provide your own base templates, put them in `allauth/layouts/entrance|manage.html`.

**Comment by lucas03** [comment]
oh, okay. And this is not documented in detail, I should just read code, right? Thank you and have a great evening.

**Comment by pennersr** [comment]
The documentation is indeed lacking in this area, pull requests to improve them are welcome.  Note that all this was done so that you can stop copying over the templates.  See for example the included example project -- it applies bootstrap styling without overriding the templates at all. Demo up and running here: https://django.demo.allauth.org/

**Comment by lucas03** [comment]
FTR I moved `account/base.html` to `allauth/layouts/manage.html`. Thanks for help

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3778
