### ISSUE TITLE
Disconnecting social account throws 500 error if not last account - adapter not initialised

### ISSUE THREAD

**Issue by enzedonline** [pennersr/django-allauth#3799]
EDIT: I see the code in the repository has been updated, it's just not updated in the package on pypi (0.62.1)

If I try to disconnect a social account when there are multiple accounts connected, I get a 500 error with the following traceback:

```bash
[13/May/2024 00:29:48] ERROR [django.request:241] Internal Server Error: /en/accounts/3rdparty/
Traceback (most recent call last):
  File ".venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File ".venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File ".venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File ".venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File ".venv/lib/python3.10/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File ".venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File ".venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File ".venv/lib/python3.10/site-packages/allauth/account/mixins.py", line 68, in post
    if form.is_valid():
  File ".venv/lib/python3.10/site-packages/django/forms/forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
  File ".venv/lib/python3.10/site-packages/django/forms/forms.py", line 192, in errors
    self.full_clean()
  File ".venv/lib/python3.10/site-packages/django/forms/forms.py", line 328, in full_clean
    self._clean_form()
  File ".venv/lib/python3.10/site-packages/django/forms/forms.py", line 349, in _clean_form
    cleaned_data = self.clean()
  File ".venv/lib/python3.10/site-packages/allauth/socialaccount/forms.py", line 57, in clean
    flows.connect.validate_disconnect(self.request, account)
  File ".venv/lib/python3.10/site-packages/allauth/socialaccount/internal/flows/connect.py", line 40, in validate_disconnect
    adapter.validate_disconnect(account, accounts)
UnboundLocalError: local variable 'adapter' referenced before assignment
```

The [`validate_disconnect`](https://github.com/pennersr/django-allauth/blob/2a9790ae3ce180c80b88358c97775a1fce15e0a8/allauth/socialaccount/internal/flows/connect.py#L17) method in `allauth/socialaccount/internal/flows/connect.py` doesn't initialise the `adapter` variable if the `is_last` condition isn't met so the call to `adapter.validate_disconnect(account, accounts)` fails:

```python
def validate_disconnect(request, account):
    """
    Validate whether or not the socialaccount account can be
    safely disconnected.
    """
    accounts = SocialAccount.objects.filter(user_id=account.user_id)
    is_last = not accounts.exclude(pk=account.pk).exists()
    if is_last:
        adapter = get_adapter()
        if allauth_settings.SOCIALACCOUNT_ONLY:
            raise adapter.validation_error("disconnect_last")
        # No usable password would render the local account unusable
        if not account.user.has_usable_password():
            raise adapter.validation_error("no_password")
        # No email address, no password reset
        if (
            account_settings.EMAIL_VERIFICATION
            == account_settings.EmailVerificationMethod.MANDATORY
        ):
            if not EmailAddress.objects.filter(
                user=account.user, verified=True
            ).exists():
                raise adapter.validation_error("no_verified_email")
    adapter.validate_disconnect(account, accounts)
```

Using django-allauth 0.62.1

**Comment by pennersr** [comment]
Fixed via 4b4d234f

**Comment by enzedonline** [comment]
Thanks.

Is there a schedule for the next release on PyPi?

**Comment by pennersr** [comment]
@enzedonline -- Yes, today :-)

**Comment by enzedonline** [comment]
Brilliant - thank you!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3799
