### ISSUE TITLE
AuthenticationBackend object has no attribute 'authenticate_header'

### ISSUE THREAD

**Issue by LeMeteore** [pennersr/django-allauth#3821]
I was trying to link a Django rest API with a Keycloak server using Django-allauth and I received an error when trying to access one of my views.

Here is the complete traceback:
```
[16/May/2024 02:58:07] "GET /api/foo/ HTTP/1.1" 500 112586
Internal Server Error: /api/foo/
Traceback (most recent call last):
  File "/home/nsukami/LAB/kcc/djangoproj2/.env/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/nsukami/LAB/kcc/djangoproj2/.env/lib/python3.12/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/nsukami/LAB/kcc/djangoproj2/.env/lib/python3.12/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/home/nsukami/LAB/kcc/djangoproj2/.env/lib/python3.12/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nsukami/LAB/kcc/djangoproj2/.env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsukami/LAB/kcc/djangoproj2/.env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsukami/LAB/kcc/djangoproj2/.env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsukami/LAB/kcc/djangoproj2/.env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsukami/LAB/kcc/djangoproj2/.env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsukami/LAB/kcc/djangoproj2/.env/lib/python3.12/site-packages/rest_framework/views.py", line 456, in handle_exception
    auth_header = self.get_authenticate_header(self.request)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsukami/LAB/kcc/djangoproj2/.env/lib/python3.12/site-packages/rest_framework/views.py", line 190, in get_authenticate_header
    return authenticators[0].authenticate_header(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AuthenticationBackend' object has no attribute 'authenticate_header'
```

The related Django setting:
```python
REST_FRAMEWORK={
        # YOUR SETTINGS
        "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
        "DEFAULT_AUTHENTICATION_CLASSES": [
            'allauth.account.auth_backends.AuthenticationBackend',
            "rest_framework.authentication.BasicAuthentication",
            "rest_framework.authentication.SessionAuthentication",
        ],
        # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.CursorPagination',
        # 'PAGE_SIZE': 100,
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.IsAuthenticated",
        ],
    },
```

I fixed the problem by editing the file: `allauth/account/auth_backends.py` and I added the following method inside the `AuthenticationBackend` class:

```python
    def authenticate_header(self, request):
        return "Token"
```

If you give me instruction on how to correctly fix the problem, I can send a pull request. Thanks a lot for your time and for everything \o/

**Comment by pennersr** [comment]
This is not an issue in allauth. Why add a `authenticate_header()` method to allauth code that is not a Django nor an allauth method? FWIW, if this works for you can always create a custom class deriving from the allauth `AuthenticationBackend` adding that method.

**Comment by LeMeteore** [comment]
> Why add a authenticate_header() method to allauth code that is not a Django nor an allauth method? 

Because I didn't know how and where to fix this problem. I didn't really understood what's said in the [documentation](https://www.django-rest-framework.org/api-guide/authentication/#custom-authentication). I quickly looked at other authentication classes and I saw they implement this method.

> FWIW, if this works for you can always create a custom class deriving from the allauth AuthenticationBackend adding that method. 

Thanks a lot for the advice. 

Any idea

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3821
