### ISSUE TITLE
Unable to reverse migrations

### ISSUE THREAD

**Issue by mcastle** [pennersr/django-allauth#3931]
Reverse migration breaks with `0008_emailaddress_unique_primary_email_fixup`

```
Operations to perform:
  Unapply all migrations: users
Running migrations:
  Rendering model states... DONE
  Unapplying convos.0001_initial... OK
  Unapplying admin.0003_logentry_add_action_flag_choices... OK
  Unapplying admin.0002_logentry_remove_auto_add... OK
  Unapplying admin.0001_initial... OK
  Unapplying account.0009_emailaddress_unique_primary_email... OK
  Unapplying account.0008_emailaddress_unique_primary_email_fixup...Traceback (most recent call last):
  File "/Users/user/devel/proj/./manage.py", line 23, in <module>
    main()
  File "/Users/user/devel/proj/./manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/Users/user/.pyenv/versions/3.12.1/envs/proj/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/user/.pyenv/versions/3.12.1/envs/proj/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/user/.pyenv/versions/3.12.1/envs/proj/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/user/.pyenv/versions/3.12.1/envs/proj/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.1/envs/proj/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.1/envs/proj/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.1/envs/proj/lib/python3.12/site-packages/django/db/migrations/executor.py", line 141, in migrate
    state = self._migrate_all_backwards(plan, full_plan, fake=fake)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.1/envs/proj/lib/python3.12/site-packages/django/db/migrations/executor.py", line 219, in _migrate_all_backwards
    self.unapply_migration(states[migration], migration, fake=fake)
  File "/Users/user/.pyenv/versions/3.12.1/envs/proj/lib/python3.12/site-packages/django/db/migrations/executor.py", line 279, in unapply_migration
    state = migration.unapply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.12.1/envs/proj/lib/python3.12/site-packages/django/db/migrations/migration.py", line 159, in unapply
    raise IrreversibleError(
django.db.migrations.exceptions.IrreversibleError: Operation <RunPython <function forwards at 0x10ae416c0>> in account.0008_emailaddress_unique_primary_email_fixup is not reversible
```

**Comment by pennersr** [comment]
That migration is simply not reversible.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3931
