### ISSUE TITLE
Impossible to save Twitter OAuth1.0a token

### ISSUE THREAD

**Issue by alexandernst** [pennersr/django-allauth#4020]
I have a fresh Django project with Django-allauth setup like this:

```python
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_STORE_TOKENS = True
SOCIALACCOUNT_ONLY = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_PROVIDERS = {
    'twitter': {
        'APP': {
            'client_id': config('TWITTER_API_KEY', default=''),
            'secret': config('TWITTER_API_SECRET', default=''),
            "key": "",
        },
        "SCOPE": [
            "tweet.read",
            "tweet.write",
            "users.read",
        ],
    },
}
```

When I try to login using Twitter, I get this error:

```
Traceback (most recent call last):
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/allauth/socialaccount/providers/oauth/views.py", line 65, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/allauth/socialaccount/providers/oauth/views.py", line 113, in dispatch
    return complete_social_login(request, login)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/allauth/socialaccount/helpers.py", line 67, in complete_social_login
    return flows.login.complete_login(request, sociallogin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/allauth/socialaccount/internal/flows/login.py", line 56, in complete_login
    return _authenticate(request, sociallogin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/allauth/socialaccount/internal/flows/login.py", line 83, in _authenticate
    ret = process_signup(request, sociallogin)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/allauth/socialaccount/internal/flows/signup.py", line 108, in process_signup
    get_adapter().save_user(request, sociallogin, form=None)
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/allauth/socialaccount/adapter.py", line 111, in save_user
    sociallogin.save(request)
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/allauth/socialaccount/models.py", line 292, in save
    self.token.save()
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/django/db/models/base.py", line 778, in save
    self._prepare_related_fields_for_save(operation_name="save")
  File "/var/www/webapp/app/venv/lib/python3.11/site-packages/django/db/models/base.py", line 1144, in _prepare_related_fields_for_save
    raise ValueError(
ValueError: save() prohibited to prevent data loss due to unsaved related object 'app'.
```

I searched for similar issues and I found [this issue](https://github.com/pennersr/django-allauth/issues/3309) and [this commit](https://github.com/pennersr/django-allauth/commit/639b46683c7b589d8020e131b72ed13fbca9c04e) that **might** be related, but I'm not too sure.

Is this a bug or am I doing something wrong?

**Comment by pennersr** [comment]
It's a bug, the issue got fixed in OAuth 2 but OAuth 1 wasn't given the same treatment. Fixed via ef8743ca

**Comment by alexandernst** [comment]
Great! Thank you for the quick response!

Can we expect a new release soon? Or do you make releases only after you reach certain amount of changes?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4020
