### ISSUE TITLE
allauth.account.middleware.AccountMiddleware breaks ASGI application

### ISSUE THREAD

**Issue by cfra** [pennersr/django-allauth#4030]
Updating from a somewhat ancient version of django-allauth, I ended up using version 0.63.6 as I am still on Django 3.2.

As part of this update I added `allauth.account.middleware.AccountMiddleware` to my `MIDDLEWARE` setting.

This leads to the following error in my gunicorn/uvicorn setup whenever a request should be handled:

```
Internal Server Error: /
Traceback (most recent call last):
  File "/home/user/comp/project/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/comp/project/.venv/lib/python3.11/site-packages/allauth/account/middleware.py", line 38, in middleware
    if _should_check_dangling_login(request, response):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/comp/project/.venv/lib/python3.11/site-packages/allauth/account/middleware.py", line 60, in _should_check_dangling_login
    content_type = response.headers.get("content-type")
                   ^^^^^^^^^^^^^^^^     
AttributeError: 'coroutine' object has no attribute 'headers'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/user/comp/project/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/comp/project/project/middleware.py", line 50, in __call__
    return self.get_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/comp/project/.venv/lib/python3.11/site-packages/asgiref/sync.py", line 254, in __call__
    return call_result.result() 
           ^^^^^^^^^^^^^^^^^^^^ 
  File "/home/user/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^  
  File "/home/user/.pyenv/versions/3.11.9/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/user/comp/project/.venv/lib/python3.11/site-packages/asgiref/sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object HttpResponse can't be used in 'await' expression
```

When removing the middleware from the stack, requests are handled just fine.

**Comment by pennersr** [comment]
Please upgrade to version 64. If the problem persists there, feel free to reopen.

**Comment by devuser132** [comment]
This bug happened to me as well. What should I do to fix it? I can't use allauth without a middleware. This error message shows up when I make a post request to django server.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4030
