### ISSUE TITLE
Error during South migration with Twitter provider

### ISSUE THREAD

**Issue by akoumjian** [pennersr/django-allauth#449]
On a fresh 1.6 project, I am attempting to initialize my database. For some reason, get_user_model() is failing during one of the twitter migrations. 

Here are the installed apps:

``` python
INSTALLED_APPS = (
    ...
    'django.contrib.auth',
    ...
    'south',
    'allauth',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.twitter',
    ...
)
```

This results in the following output and error during `./manage.py migrate --all`:

``` sh
(announce)~/Code/announce(master ✗) ./manage.py migrate --all
Running migrations for socialaccount:
 - Migrating forwards to 0011_auto__chg_field_socialtoken_token.
 > socialaccount:0001_initial
 > twitter:0001_initial
 > twitter:0002_snowflake
 > socialaccount:0002_genericmodels
 > twitter:0003_tosocialaccount
 - Migration 'twitter:0003_tosocialaccount' is marked for no-dry-run.
 > socialaccount:0003_auto__add_unique_socialaccount_uid_provider
 > socialaccount:0004_add_sites
 > socialaccount:0005_set_sites
 - Migration 'socialaccount:0005_set_sites' is marked for no-dry-run.
 > socialaccount:0006_auto__del_field_socialapp_site
 > socialaccount:0007_auto__add_field_socialapp_client_id
 > socialaccount:0008_client_id
 - Migration 'socialaccount:0008_client_id' is marked for no-dry-run.
 > socialaccount:0009_auto__add_field_socialtoken_expires_at
 > socialaccount:0010_auto__chg_field_socialtoken_token
 > socialaccount:0011_auto__chg_field_socialtoken_token
 - Loading initial data for socialaccount.
Installed 0 object(s) from 0 fixture(s)
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/aleck/.virtualenvs/announce/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/aleck/.virtualenvs/announce/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/aleck/.virtualenvs/announce/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/aleck/.virtualenvs/announce/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/aleck/.virtualenvs/announce/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/Users/aleck/.virtualenvs/announce/lib/python2.7/site-packages/south/migration/__init__.py", line 179, in migrate_app
    Migrations.invalidate_all_modules()
  File "/Users/aleck/.virtualenvs/announce/lib/python2.7/site-packages/south/migration/base.py", line 237, in invalidate_all_modules
    migration.invalidate_module()
  File "/Users/aleck/.virtualenvs/announce/lib/python2.7/site-packages/south/migration/base.py", line 381, in invalidate_module
    reload(self.migration())
  File "/Users/aleck/.virtualenvs/announce/lib/python2.7/site-packages/allauth/socialaccount/migrations/0001_initial.py", line 11, in <module>
    User = get_user_model()
  File "/Users/aleck/.virtualenvs/announce/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 122, in get_user_model
    raise ImproperlyConfigured("AUTH_USER_MODEL refers to model '%s' that has not been installed" % settings.AUTH_USER_MODEL)
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'auth.User' that has not been installed
```

**Comment by cyberjoac** [comment]
Any solution to this issue?
Thanks

**Comment by ratijas** [comment]
aaaaaaaaaand it still happens.

**Comment by ahmed-almawardy** [comment]
till now!

**Comment by solow-crypt** [comment]
bruh whyyyyyy

**Comment by Salmanulhamdan** [comment]
any body have solution

**Comment by siavashoh** [comment]
I also got this error and solved it by renaming the file name of the model. I don't know why. I test it several times and reverted it to the old name and got that error. then after renaming, it was solved

for more information, my model's file's name was "invite"

**Comment by shahsuvarli** [comment]
Still looking for an answer

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/449
