### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'my.MyUser' that has not been installed

### ISSUE THREAD

**Issue by lucacorti** [pennersr/django-allauth#450]
After upgrading to Django 1.6 I get this error when running migrate:

```
$ python manage.py migrate
Running migrations for socialaccount:
- Nothing to migrate.
 - Loading initial data for socialaccount.
Installed 0 object(s) from 0 fixture(s)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/user/.virtualenvs/my/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/user/.virtualenvs/my/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/user/.virtualenvs/my/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/user/.virtualenvs/my/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/user/.virtualenvs/my/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/Users/user/.virtualenvs/my/lib/python2.7/site-packages/south/migration/__init__.py", line 179, in migrate_app
    Migrations.invalidate_all_modules()
  File "/Users/user/.virtualenvs/my/lib/python2.7/site-packages/south/migration/base.py", line 237, in invalidate_all_modules
    migration.invalidate_module()
  File "/Users/user/.virtualenvs/my/lib/python2.7/site-packages/south/migration/base.py", line 381, in invalidate_module
    reload(self.migration())
  File "/Users/user/.virtualenvs/my/lib/python2.7/site-packages/allauth/socialaccount/migrations/0001_initial.py", line 11, in <module>
    User = get_user_model()
  File "/Users/user/.virtualenvs/my/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 122, in get_user_model
    raise ImproperlyConfigured("AUTH_USER_MODEL refers to model '%s' that has not been installed" % settings.AUTH_USER_MODEL)
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'my.MyUser' that has not been installed
```

**Comment by SaurabhGujjar** [comment]
Did you register all your models in admin.py file. It worked for me.

**Comment by siavashoh** [comment]
I also got this error and solved it by renaming the file name of the model. I don't know why. I test it several times and reverted it to the old name and got that error. then after renaming, it was solved

for more information, my model's file's name was "invite"

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/450
