### ISSUE TITLE
Socialaccount initial migrations fail on MySQL 5.5.34/InnoDB

### ISSUE THREAD

**Issue by andyn** [pennersr/django-allauth#472]
When creating the tables for the first time with MySQL 5.5.34 running the InnoDB backend, the migrate process fails:

```
$ ./manage.py syncdb
--- snipped ---
$ ./manage.py migrate
Running migrations for socialaccount:
 - Migrating forwards to 0011_auto__chg_field_socialtoken_token.
 > socialaccount:0001_initial
 > socialaccount:0002_genericmodels
 > openid:0001_initial
 > openid:0002_tosocialaccount
 - Migration 'openid:0002_tosocialaccount' is marked for no-dry-run.
 > facebook:0001_initial
 > facebook:0002_auto__add_facebookaccesstoken__add_unique_facebookaccesstoken_app_acco
 > facebook:0003_tosocialaccount
 - Migration 'facebook:0003_tosocialaccount' is marked for no-dry-run.
 > socialaccount:0003_auto__add_unique_socialaccount_uid_provider
 > socialaccount:0004_add_sites
 > socialaccount:0005_set_sites
 - Migration 'socialaccount:0005_set_sites' is marked for no-dry-run.
 > socialaccount:0006_auto__del_field_socialapp_site
FATAL ERROR - The following SQL query failed: ALTER TABLE `socialaccount_socialapp` DROP COLUMN `site_id` CASCADE;
The error was: (1025, "Error on rename of './cloud/#sql-729c_3e' to './cloud/socialaccount_socialapp' (errno: 150)")
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/myapp/virtualenv.myapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/myapp/virtualenv.myapp/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/myapp/virtualenv.myapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/myapp/virtualenv.myapp/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/myapp/virtualenv.myapp/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/myapp/virtualenv.myapp/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/myapp/virtualenv.myapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 254, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/myapp/virtualenv.myapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 329, in migrate_many
    result = self.migrate(migration, database)
  File "/home/myapp/virtualenv.myapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/home/myapp/virtualenv.myapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/home/myapp/virtualenv.myapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 93, in run_migration
    print(self.run_migration_error(migration))
  File "/home/myapp/virtualenv.myapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 323, in run_migration_error
    (self.format_backwards(migration), extra_info))
  File "/home/myapp/virtualenv.myapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 310, in format_backwards
    self.backwards(migration)()
  File "/home/myapp/virtualenv.myapp/local/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/home/myapp/virtualenv.myapp/local/lib/python2.7/site-packages/allauth/socialaccount/migrations/0006_auto__del_field_socialapp_site.py", line 18, in backwards
    raise RuntimeError("Cannot reverse this migration. 'SocialApp.site' and its values cannot be restored.")
RuntimeError: Cannot reverse this migration. 'SocialApp.site' and its values cannot be restored.
```

The site_id column cannot be removed manually, either (due to key constraints), nor can the MUL index be removed manually in MySQL. For the record, the migrations work fine in SQLite 3.7.9. The only workaround is to remove the migrations directories from the allauth application manually.

Additionally, the following PyPI packages have been installed:

```
$ pip freeze
Django==1.6
MySQL-python==1.2.4
PIL==1.1.7
Plata==1.1.0
South==0.8.4
amqp==1.3.3
anyjson==0.3.3
argparse==1.2.1
billiard==3.3.0.8
celery==3.1.5
distribute==0.7.3
django-allauth==0.15.0
django-appconf==0.6
django-compressor==1.3
django-guardian==1.1.1
django-http-proxy==0.3.2
httplib2==0.8
kombu==3.0.6
librabbitmq==1.0.3
mock==1.0.1
oauthlib==0.6.0
python-openid==2.2.5
pytz==2013.8
requests==2.0.1
requests-oauthlib==0.4.0
simplejson==3.3.1
six==1.4.1
uWSGI==1.9.20
wsgiref==0.1.2
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/472
