### ISSUE TITLE
AttributeError: 'module' object has no attribute 'UNIQUE_EMAIL'

### ISSUE THREAD

**Issue by aztrock** [pennersr/django-allauth#474]
python version: 3.2.3

synchronizing

$ python manage.py syncdb
(billing)aztrock:~/workspace/billing/billing$ python manage.py syncdb
/home/aztrock/workspace/billing/billing/apps/ajax.py:2: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/aztrock/workspace/billing/local/lib/python3.2/site-packages/django/core/management/**init**.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/aztrock/workspace/billing/local/lib/python3.2/site-packages/django/core/management/**init**.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/aztrock/workspace/billing/local/lib/python3.2/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/home/aztrock/workspace/billing/local/lib/python3.2/site-packages/django/core/management/base.py", line 284, in execute
    self.validate()
  File "/home/aztrock/workspace/billing/local/lib/python3.2/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/home/aztrock/workspace/billing/local/lib/python3.2/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/home/aztrock/workspace/billing/local/lib/python3.2/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/home/aztrock/workspace/billing/local/lib/python3.2/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/home/aztrock/workspace/billing/local/lib/python3.2/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/usr/lib/python3.2/importlib/__init__.py", line 124, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 821, in _gcd_import
    loader.load_module(name)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 436, in load_module
    return self._load_module(fullname)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 141, in decorated
    return fxn(self, module, _args, *_kwargs)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 342, in _load_module
    exec(code_object, module.__dict__)
  File "/home/aztrock/workspace/billing/local/lib/python3.2/site-packages/allauth/account/models.py", line 21, in <module>
    class EmailAddress(models.Model):
  File "/home/aztrock/workspace/billing/local/lib/python3.2/site-packages/allauth/account/models.py", line 25, in EmailAddress
    email = models.EmailField(unique=app_settings.UNIQUE_EMAIL,
AttributeError: 'module' object has no attribute 'UNIQUE_EMAIL'

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/474
