### ISSUE TITLE
South error with Twitter provider

### ISSUE THREAD

**Issue by affan2** [pennersr/django-allauth#550]
The below error occurs every time I run a migration for schema changes to any app within my project 

```
./manage.py migrate articles
Migration 'socialaccount:0003_auto__add_unique_socialaccount_uid_provider' depends on unknown migration 'twitter:0003_tosocialaccount'.
Traceback (most recent call last):
  File "manage.py", line 33, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 229, in run_from_argv
    stderr.write('%s: %s' % (e.__class__.__name__, e))
TypeError: __str__ returned non-string (type NoneType)
```

The only way to proceed is to remove `'allauth.socialaccount.providers.twitter'` from `INSTALLED_APPS` in the settings file.

I've tried the solutions presented in ticket https://github.com/pennersr/django-allauth/issues/449 but no joy with either solution.

I realise this is likely a South issue and I have also submitted a ticket there.

Running Django 1.5.4, South 0.8.4 and django-allauth 0.15.0.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/550
