### ISSUE TITLE
cannot import name BaseSignupForm error

### ISSUE THREAD

**Issue by luzfcb** [pennersr/django-allauth#572]
Hello I'm having trouble creating a custom signup form as very briefly described in the documentation.

I created a new project using [cookiecutter-django](https://github.com/pydanny/cookiecutter-django)

I created a new app called `myapp` and put `myaap` into `INSTALED_APPS` in settings.py file

within the app folder `myapp`, i created a `forms.py` file.

``` python
from allauth.account.forms import BaseSignupForm

class SignupForm(BaseSignupForm):

    def signup(self, request, user):
        print('#######################')
        print('here', self.__class__.__name__)
        print('#######################')
```

put `ACCOUNT_SIGNUP_FORM_CLASS = "myapp.forms.SignupForm"` into settings.py file

After runserver, result in this

``` python
/home/sutransdev/1envs_virtualenv/sisposto/bin/python2.7 /home/sutransdev/projetos/posto/sisposto/sisposto/manage.py runserver 127.0.0.1:8000
django-configurations version 0.8, using configuration 'Local'
Validating models...

Unhandled exception in thread started by <function wrapper at 0x28df500>
Traceback (most recent call last):
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 93, in wrapper
    fn(*args, **kwargs)
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 101, in inner_run
    self.validate(display_num_errors=True)
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/debug_toolbar/models.py", line 63, in <module>
    patch_root_urlconf()
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/debug_toolbar/models.py", line 51, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 480, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 310, in app_dict
    self._populate()
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 262, in _populate
    for pattern in reversed(self.url_patterns):
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/sutransdev/projetos/posto/sisposto/sisposto/config/urls.py", line 29, in <module>
    url(r'^accounts/', include('allauth.urls')),
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/allauth/urls.py", line 8, in <module>
    urlpatterns = patterns('', url('^', include('allauth.account.urls')))
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/allauth/account/urls.py", line 4, in <module>
    from . import views
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/allauth/account/views.py", line 21, in <module>
    from .forms import AddEmailForm, ChangePasswordForm
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/allauth/account/forms.py", line 198, in <module>
    class BaseSignupForm(_base_signup_form_class()):
  File "/home/sutransdev/1envs_virtualenv/sisposto/local/lib/python2.7/site-packages/allauth/account/forms.py", line 179, in _base_signup_form_class
    ' "%s"' % (fc_module, e))
django.core.exceptions.ImproperlyConfigured: Error importing form class myapp.forms: "cannot import name BaseSignupForm"

```

What is the correct way to create this form?
The form fields defined in "allauth / account / forms.py" may have been designed to be reusable? 
I tried using SignupForm BaseSignupForm in place, but resulted in the same error.

A good explanation in the documentation on how to do this would be very welcome, and probably would avoid questions like mine.

Thanks for this project.

**Comment by tjwudi** [comment]
Also having this issue but inheriting from `SignupForm` instead, just want to override `username` field to couple with #1321.

I suggest we re-open this issue @pennersr, inheriting from `BaseSignupForm` and `SignupForm` should be allowed for minimal customization needs.

**Comment by JulianSchneider** [comment]
Sorry for digging this up, but if WANT to override the Signup form, because i want to remove the placeholders, how would i go about that?

**Comment by AlvaroIHS** [comment]
@JulianSchneider I done it with javascript: 
$('input[type=password]').removeAttr('placeholder');

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/572
