### ISSUE TITLE
Can't get it to work with Google AppEngine

### ISSUE THREAD

**Issue by bill-pairaktaridis** [pennersr/django-allauth#720]
So, my code works perfectly with the Django local server (manage.py runserver) and it creates my user, no problem. However, running it either with AppEngine's local server or on the AppEngine cloud, it gets stuck at /accounts/social/signup/. Locally, I get something like this:

```
INFO     2014-09-16 13:22:04,912 connectionpool.py:635] Starting new HTTPS connection (1): graph.facebook.com
ERROR    2014-09-16 13:22:05,172 views.py:78] Error accessing FB user profile
Traceback (most recent call last):
  File "/home/bill/work/ellinopoula/src/ellinopoula/allauth/socialaccount/providers/facebook/views.py", line 73, in login_by_token
    login = fb_complete_login(request, app, token)
  File "/home/bill/work/ellinopoula/src/ellinopoula/allauth/socialaccount/providers/facebook/views.py", line 27, in fb_complete_login
    resp.raise_for_status()
  File "/home/bill/work/ellinopoula/src/ellinopoula/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 400 Client Error: Bad Request
INFO     2014-09-16 13:22:05,187 module.py:639] default: "POST /accounts/facebook/login/token/ HTTP/1.1" 200 8609

```

Could there be some import I'm missing? AppEngine is weird in the way that it needs the packages linked to your app's folder, whereas Django's web server just works with a virtual environment.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/720
