### ISSUE TITLE
data args is getting a unicode

### ISSUE THREAD

**Issue by zkanda** [pennersr/django-allauth#738]
Hello everyone, I have this weird issue sometimes when someone signs-up with my app. How come the data args is getting a unicode? Another thing is that I can't replicate it on my dev machine.

Here's a traceback

``` bash
Traceback (most recent call last):

  File "/var/local/sites/project_folder/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/var/local/sites/project_folder/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)

  File "/var/local/sites/project_folder/venv/local/lib/python2.7/site-packages/allauth/socialaccount/views.py", line 30, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)

  File "/var/local/sites/project_folder/venv/local/lib/python2.7/site-packages/allauth/account/views.py", line 62, in dispatch
    **kwargs)

  File "/var/local/sites/project_folder/venv/local/lib/python2.7/site-packages/allauth/account/views.py", line 133, in dispatch
    **kwargs)

  File "/var/local/sites/project_folder/venv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)

  File "/var/local/sites/project_folder/venv/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 171, in post
    return self.form_valid(form)

  File "/var/local/sites/project_folder/venv/local/lib/python2.7/site-packages/allauth/socialaccount/views.py", line 42, in form_valid
    form.save(self.request)

  File "/var/local/sites/project_folder/venv/local/lib/python2.7/site-packages/allauth/socialaccount/forms.py", line 35, in save
    user = adapter.save_user(request, self.sociallogin, form=self)

  File "/var/local/sites/project_folder/venv/local/lib/python2.7/site-packages/allauth/socialaccount/adapter.py", line 50, in save_user
    get_account_adapter().save_user(request, u, form)

  File "/var/local/sites/project_folder/venv/local/lib/python2.7/site-packages/allauth/account/adapter.py", line 176, in save_user
    first_name = data.get('first_name')

AttributeError: 'unicode' object has no attribute 'get'


<WSGIRequest
path:/accounts/social/signup/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'username': [u'test'], u'first_name': [u'test_first'], u'last_name': [u'test_ast'], u'gender': [u'f'], u'email': [u'test@gmail.com'], u'airport': [u'Charles De Gaulle - (CDG) France'], u'agree_policy': [u'on'], u'country': [u'FR'], u'csrfmiddlewaretoken': [u'gdwi8DvSdkA21H5AJzBkDRPXLSAVsw3U']}>,
COOKIES:{'__cfduid': 'd198d68bb9be76b50f707283440edbace1413060960514',
 'csrftoken': 'gdwi8DvSdkA21H5AJzBkDRPXLSAVsw3U',
 'fbsr_502779676474659': '2mTo359lZiW2bnBIOGIV34haZ8Yqqatg6ZkfhhCMvLM.eyJhbGdvcml0aG0iOiJITUFDLVNIQTI1NiIsImNvZGUiOiJBUUJ6a1cxdmwwd3V2bTNUa21ad0FHR3dnbjFxRlZnb2VKMGw1UXA3M2Y0SjdBUllKek5UQkpGbWd6U1A0Wk14ZzdPQ3JPb2hjSkt4WWRzREFjRWNwV3RoS3kwSTZmMWJGLTIzSnVsa2R5RjB5RFpSZHFWaGNMeTFkZkp1ejNLbGVtR2t5cVlYQzNnX2J4ckFmTUJQcFhSSG96d1hCeEpEZVNXWU1tWG84Yk9URWdoQTAwTVlzblRJZHhHODdjclh6V3JYcWhoLVpCbmUxNVQxLS1UV1FRZ1hkYTc0QzFGcjh6aTJNQWZKaldZMEdMaXJVeFY0VFhBODBXYURtWk5HcHVYQ1Ric1RFcVZZd1llcE90anZkNUgwb3pnejZ4LXRZMDdFRVIwdDNsTnBWLV9kYTZrSTF4ZUJiTXZuVFBsZzVLbHI3cThyYjBrcFhWOGlqUWRxQ3JIQiIsImlzc3VlZF9hdCI6MTQxMzA2MTA5MiwidXNlcl9pZCI6IjEwMDAwNDY1NzQ3NjY2NSJ9',
 'sessionid': 'x4o0yaonspy6k6zecb17gbas3srtsqo7'},
META:{'CONTENT_LENGTH': '254',
 'CONTENT_TYPE': 'application/x-www-form-urlencoded',
 u'CSRF_COOKIE': u'gdwi8DvSdkA21H5AJzBkDRPXLSAVsw3U',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8,it;q=0.6,ja;q=0.4,ko;q=0.2,fr;q=0.2',
 'HTTP_CACHE_CONTROL': 'max-age=0',
 'HTTP_CF_CONNECTING_IP': '78.250.142.89',
 'HTTP_CF_IPCOUNTRY': 'FR',
 'HTTP_CF_RAY': '177df9fd0f4a1025-CDG',
 'HTTP_CF_VISITOR': '{"scheme":"https"}',
 'HTTP_CONNECTION': 'close',
 'HTTP_COOKIE': '__cfduid=d198d68bb9be76b50f707283440edbace1413060960514; sessionid=x4o0yaonspy6k6zecb17gbas3srtsqo7; csrftoken=gdwi8DvSdkA21H5AJzBkDRPXLSAVsw3U; fbsr_502779676474659=2mTo359lZiW2bnBIOGIV34haZ8Yqqatg6ZkfhhCMvLM.eyJhbGdvcml0aG0iOiJITUFDLVNIQTI1NiIsImNvZGUiOiJBUUJ6a1cxdmwwd3V2bTNUa21ad0FHR3dnbjFxRlZnb2VKMGw1UXA3M2Y0SjdBUllKek5UQkpGbWd6U1A0Wk14ZzdPQ3JPb2hjSkt4WWRzREFjRWNwV3RoS3kwSTZmMWJGLTIzSnVsa2R5RjB5RFpSZHFWaGNMeTFkZkp1ejNLbGVtR2t5cVlYQzNnX2J4ckFmTUJQcFhSSG96d1hCeEpEZVNXWU1tWG84Yk9URWdoQTAwTVlzblRJZHhHODdjclh6V3JYcWhoLVpCbmUxNVQxLS1UV1FRZ1hkYTc0QzFGcjh6aTJNQWZKaldZMEdMaXJVeFY0VFhBODBXYURtWk5HcHVYQ1Ric1RFcVZZd1llcE90anZkNUgwb3pnejZ4LXRZMDdFRVIwdDNsTnBWLV9kYTZrSTF4ZUJiTXZuVFBsZzVLbHI3cThyYjBrcFhWOGlqUWRxQ3JIQiIsImlzc3VlZF9hdCI6MTQxMzA2MTA5MiwidXNlcl9pZCI6IjEwMDAwNDY1NzQ3NjY2NSJ9',
 'HTTP_HOST': 'www.project.org',
 'HTTP_ORIGIN': 'https://www.project.org',
 'HTTP_REFERER': 'https://www.project.org/accounts/social/signup/',
 'HTTP_TRUE_CLIENT_IP': '0',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36',
 'HTTP_X_FORWARDED_FOR': '78.255.142.89, 108.162.248.47, 172.17.12.1',
 'HTTP_X_FORWARDED_PROTO': 'https',
 'HTTP_X_REAL_IP': '108.162.248.47',
 'PATH_INFO': u'/accounts/social/signup/',
 'QUERY_STRING': '',
 'RAW_URI': '/accounts/social/signup/',
 'REMOTE_ADDR': '',
 'REQUEST_METHOD': 'POST',
 'SCRIPT_NAME': u'',
 'SERVER_NAME': 'www.project.org',
 'SERVER_PORT': '443',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'gunicorn/19.1.1',
 'gunicorn.socket': <socket._socketobject object at 0x691fe50>,
 'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWraper object at 0x56214d0>,
 'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
 'wsgi.input': <gunicorn.http.body.Body object at 0x5621190>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'https',
 'wsgi.version': (1, 0)}>
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/738
