### ISSUE TITLE
test_password_forgotten_url_protocol fails in 0.19.1 and master

### ISSUE THREAD

**Issue by yosemitebandit** [pennersr/django-allauth#837]
cloned from github and ran `pip install -r requirements.txt`.  (I've also seen this test case fail on the version from pypi.)

```
$ python manage.py test allauth.account.tests.AccountTests

Creating test database for alias 'default'...
F
======================================================================
FAIL: test_password_forgotten_url_protocol (allauth.account.tests.AccountTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matt/django-allauth/allauth/account/tests.py", line 189, in test_password_forgotten_url_protocol
    self.assertTemplateUsed(resp, 'account/password_reset_from_key.html')
  File "/home/matt/conf/venvs/allauth/local/lib/python2.7/site-packages/django/test/testcases.py", line 538, in assertTemplateUsed
    self.fail(msg_prefix + "No templates used to render the response")
AssertionError: No templates used to render the response

----------------------------------------------------------------------
Ran 1 test in 0.189s

FAILED (failures=1)
```

I believe [this line](https://github.com/pennersr/django-allauth/blob/master/allauth/account/tests.py#L187) needs to change -- we should search for `/accounts/password/reset/`, not just `/password/reset/`.

**Comment by yosemitebandit** [comment]
annnd I can't reproduce anymore!  probably something with my setup, sorry!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/837
