### ISSUE TITLE
Errror with allauth.socialaccount and Django 1.7

### ISSUE THREAD

**Issue by xerosis** [pennersr/django-allauth#850]
As soon as I uncomment allauth.socialaccount when Django is running or when it's not and I try to makemigrations I get the following error:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/__init__.py", line 23, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/allauth/socialaccount/admin.py", line 10, in <module>
    class SocialAppForm(forms.ModelForm):
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 284, in __new__
    opts.help_texts, opts.error_messages)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 210, in fields_for_model
    formfield = f.formfield(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 1064, in formfield
    return super(CharField, self).formfield(**defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 823, in formfield
    defaults['choices'] = self.get_choices(include_blank=include_blank)
import django
from django.contrib import admin
from django import forms

from allauth.account.adapter import get_adapter

from .models import SocialApp, SocialAccount, SocialToken
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 733, in get_choices
    choices = list(self.choices) if self.choices else []
TypeError: Error when calling the metaclass bases
    'instancemethod' object is not iterable

**Comment by Routhinator** [comment]
+1 Issue confirmed here.

**Comment by Routhinator** [comment]
Fix (or workaround, depending on your view) here: http://stackoverflow.com/questions/27261030/migration-error-with-django-1-7-1

**Comment by xerosis** [comment]
Even commenting everything out doesn't work for me, my error is different to that one as well.

**Comment by pennersr** [comment]
Closing until there is something more conclusive to go on that there is an issue in allauth here..

**Comment by radhakrishnancegit** [comment]
I got the same error when i add a new IntegerField(choices=[]) to the model and create a form out of the model.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/850
