### ISSUE TITLE
socialaccount migration: TypeError: b'{}' is not JSON serializable

### ISSUE THREAD

**Issue by synotna** [pennersr/django-allauth#902]
Python 3.4.3
Django 1.8

```python
Operations to perform:
  Synchronize unmigrated apps: facebook, allauth, staticfiles, rest_framework, rest_auth, messages, registration
  Apply all migrations: sites, auth, sessions, events, admin, authtoken, socialaccount, account, contenttypes
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying socialaccount.0002_auto_20150403_2348...Traceback (most recent call last):
  File "/home/antony/.pyenv/versions/tnd-backend/lib/python3.4/site-packages/allauth/socialaccount/fields.py", line 48, in get_prep_value
    return json.dumps(value)
  File "/home/antony/.pyenv/versions/3.4.3/lib/python3.4/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/home/antony/.pyenv/versions/3.4.3/lib/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/antony/.pyenv/versions/3.4.3/lib/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "/home/antony/.pyenv/versions/3.4.3/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'{}' is not JSON serializable
```

**Comment by pennersr** [comment]
Likely due to https://github.com/pennersr/django-allauth/pull/881

**Comment by rebkwok** [comment]
I am also getting this error with django 1.8 and all-auth 0.19.1

**Comment by HEdingfield** [comment]
@rebkwok same deal for me, works now! Thanks for the tip.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/902
