### ISSUE TITLE
settings.TEMPLATE_CONTEXT_PROCESSORS deprecated in Django 1.8

### ISSUE THREAD

**Issue by guettli** [pennersr/django-allauth#911]
I wanted to try django-allauth today, but failed:

```
/home/guettli/projects/foo/bin/python /home/guettli/projects/foo/src/foo/sosoproject/manage.py runserver
Traceback (most recent call last):
  File "/home/guettli/projects/foo/src/foo/sosoproject/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/guettli/projects/foo/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/guettli/projects/foo/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/guettli/projects/foo/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/guettli/projects/foo/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/guettli/projects/foo/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/guettli/projects/foo/local/lib/python2.7/site-packages/django_allauth-0.19.1-py2.7.egg/allauth/account/models.py", line 15, in <module>
    from .. import app_settings as allauth_app_settings
  File "/home/guettli/projects/foo/local/lib/python2.7/site-packages/django_allauth-0.19.1-py2.7.egg/allauth/app_settings.py", line 9, in <module>
    raise ImproperlyConfigured("socialaccount context processor "
django.core.exceptions.ImproperlyConfigured: socialaccount context processor not found in settings.TEMPLATE_CONTEXT_PROCESSORS.See settings.py instructions here: https://github.com/pennersr/django-allauth#installation
Process finished with exit code 1
```

According to the docs this setting is deprecated:
https://docs.djangoproject.com/en/1.8/ref/settings/#template-context-processors

What should the settings look like for Django 1.8?

Mine look like this:
```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'allauth.account.context_processors.account',
                'allauth.socialaccount.context_processors.socialaccount',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```

**Comment by pennersr** [comment]
New-style settings are only supported in current master. Until that is released, use old-style `settings.TEMPLATE_CONTEXT_PROCESSORS` (or switch to master).

**Comment by lucas03** [comment]
I can confirm that version 0.23 works ok with django 1.8

**Comment by guettli** [comment]
Good news. Thank you.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/911
